kubevela/catalog

hack/build.sh
hack/test.sh

Fixes build and test scripts.
build.sh and test.sh cannot meet the loop condition after using cd.

Fix the problem of loop exit

---

traits/metricstrait/api/v1alpha1/metricstrait_webhook.go
traits/metricstrait/controllers/metricstrait_controller.go
traits/metricstrait/controllers/metricstrait_controller_integration_test.go
traits/metricstrait/controllers/metricstrait_webhook_test.go
traits/metricstrait/controllers/suite_test.go
traits/metricstrait/go.mod
traits/metricstrait/main.go

Move the git module name to match github name. The kubebuilder generated module name doesn't match github name
running UT and integration test
I have:

[Trait] Move the git module name to match github name

---

.github/workflows/go.yml

Error: Unable to process command '##[add-path]/home/runner/configurator/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt
into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS`
environment variable to `true`.
To fix issue #67

Fix CI issue: The `add-path` command is disabled

---

traits/hpatrait/controllers/horizontalpodautoscalertrait_controller.go

due to workload child resource create not timely lead to  not generate hpa, should wait 30s, go on reconciling.

hpa trait may econcile before child resource

---

addons/terraform/template.yaml

Upgrade Terraform controller release to v0.2.8, which is the same
version to KubeVela release 1.1
I have:

Upgrade Terraform controller release

---

addons/terraform-provider-alibaba/resources/alibaba-account-creds.cue

In #132, the defiitions of ststoken is removed, but it wasn't removed
from the stringdata of the secret
I have:

Fix: remove ststoken from stringdata of a secret

---

addons/terraform-provider-alibaba/resources/parameter.cue

The parameter `ALICLOUD_DEFAULT_REGION` doesn't match the secret key
`ALICLOUD_REGION`
I have:

Fix the parameter `ALICLOUD_REGION` from terraform alibaba addon

---

addons/observability/resources/grafana.cue
addons/observability/resources/loki.cue

More than one properties are not coupled with {}, which leads to the
renderring error for components and traits
I have:

Fix properties error for Grafana and Loki in Addon observability

---

addons/observability/resources/kube-state-metrics.cue

The component kube-state-metrics in .cue format is wrong, which leads
to the failure of rendering
I have:

Correct .cue for kube-state-metrics component

---

addons/terraform-provider-alibaba/template.yaml

- This will help organize all addon application in one namespace
- Disabling terraform provider addon will fail as the addon could not
be found in vela-system
I have:

Change terraform provider's namespace to `vela-system`

---

addons/terraform-provider-alibaba/resources/alibaba-provider.cue

The provider name should be `default`, instead of `alicloud` for
terraform alibaba cloud provider
I have:

Fix the name of Provider for terraform alibaba provider

---

addons/fluxcd/definitions/helm-release-def.yaml

Add helm install timeout paramter. This parameter default to 10m. Default value is 5m when not configured.
ref doc https://fluxcd.io/docs/components/helm/helmreleases/#specification
Fixes https://github.com/oam-dev/kubevela/issues/2729
I have:

[Addon] Increase helm install timeout to 10min, add parameter

---

addons/observability/resources/grafana.cue

The namespace of Grafana should also be in vela-system
I have:

Fix: change the namespace of Grafana

---

addons/observability/resources/parameter.cue
addons/observability/resources/prometheus-server.cue

Users doesn't need to set pvc name and size for Prometheus alarm
and server. But have to set a default stroage class for a Kubernetes
Cluster.
I have:

Reduce the parameters for Add-on Observability

---

addons/observability/metadata.yaml

Use `deployTo.customize_runtime_cluster` in add-on metadata
to mark it will need to customize runtime clusters to enable
the addon
I have:

Observability add-on needs to customize runtime

---

addons/terraform-alibaba/schemas/component-uischema-alibaba-ack.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-ask.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-eip.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-oss.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-rds.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-redis.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-sls-project.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-sls-store.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-vpc.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-vswitch.yaml
addons/terraform-aws/definitions/terraform-aws-s3.yaml
addons/terraform-aws/schemas/component-uischema-aws-s3.yaml
addons/terraform-azure/schemas/component-uischema-azure-database-mariadb.yaml
hack/addons/README.md
hack/addons/gen-addon-ui-schema.go

Added ischemas  for all Terraform typed ComponentDefintions to hide
some properties when setting the components
I have:

Add UI schema to hide some fields of all Terraform Components

---

addons/velaux/resources/parameter.cue

Feat: change velaux default version to v1.2.0-beta.2

---

addons/terraform/template.yaml

- Fix unproper serviceaccount settings
When there are two applications, who have the same application name, but
different namespace names, the second one's service account will use
the first one. But the clusterrole's namespace isn't in its namespace.
It will lack all authority to perform any operations when running
Terraform applying.
- Support validating stsToken
Besides validating ak/sk, support stsToken
I have:

[addon] Upgrade terraform addon

---

addons/fluxcd/definitions/helm-release-def.yaml

When installing helm failed，the application can only get rough information from the custom status of the helm component, like this:
```
services:
- healthy: false
message: |-
Fetch repository successfully, Create helm release fail, message: install retries exhausted
name: msp-msp
```
expect:
```
services:
- healthy: false
message: |-
Fetch repository successfully, Create helm release fail, message: install retries exhausted, Helm install failed: timed out waiting for the condition
Last Helm logs:
creating 5 resource(s)
beginning wait for 5 resources with timeout of 5m0s
Deployment is not ready: default/msp-portal. 0 out of 3 expected pods are ready
name: msp-msp
workloadDefinition:
apiVersion: ""
kind: ""
```
I have:

Feat: patch helm release definition custom status

---

addons/terraform-alibaba/resources/parameter.cue

Make the way of setting parameters ALICLOUD_ACCESS_KEY and
ALICLOUD_SECRET_KEY in different descriptions.
I have:

Don't repeat the description for two parameters

---

.github/workflows/addon-test.yaml
Makefile
test/e2e-test/addon/mock_server.go
test/e2e-test/hack/addon-vela-test.sh

The e2e test should curl the mock server ip to wait until the server startup acctually.
I have:

Fix: mocker server have some chance to startup failed

---

addons/terraform/metadata.yaml
addons/terraform/resources/parameter.cue
addons/terraform/resources/terraform-controller.cue
addons/terraform/template.yaml

Added a parameter `github-blocked` for Addon Terraform to decide
whether to replace Github to Gitee where Terraform modules are stored.
I have:

[Addon] Support use to choose whether speed up Github

---

addons/terraform/resources/terraform-controller.cue

Fixed the issues:
* Make provider status consistent with that of Configuration by  in https://github.com/oam-dev/terraform-controller/pull/220
* Set default value for environment names by  in https://github.com/oam-dev/terraform-controller/pull/223
* Correct `make alibaba-credentials` target by  in https://github.com/oam-dev/terraform-controller/pull/221
* Fix: allow Configuration to delete when Provider is not ready by  in https://github.com/oam-dev/terraform-controller/pull/222
I have:

Upgrade the version of addon Terraform

---

addons/velaux/metadata.yaml

The description of addon velaux contains an extra blank character
and is too long
Fix #224
I have:

[Addon] Fix the description of addon velaux

---

addons/terraform-aws/definitions/terraform-aws-rds.yaml

Added another Terraform typed ComponentDefinition AWS RDS
I have:

Add Cloud Resource: AWS RDS

---

experimental/addons/observability/resources/grafana.cue
experimental/addons/observability/resources/parameter.cue

Signed-off-by: zhukunshuai <jookunshuai@gmail.com>
Fixes https://github.com/oam-dev/kubevela/issues/3188
I have:

[Addon] Make grafana's service type configurable in addon

---

addons/fluxcd/definitions/helm-release-def.yaml
addons/fluxcd/resources/deployment/helm-controller.yaml

1. speed up helm release update status
We used fluxcd parameter wrongly before. We use helmRepo pull interval which is helm chart update interval as  helmRelease reconcile the default value is 5min .This due to helm release take a long time after all pods have ready. So introduce a new parameter `interval` as reconcile interval.
2. solve helm controller error log abort notification. This is because we have reduce notification controller before.
I have:

Fix: helm release  status upadete slow problem and log error

---

addons/velaux/resources/apiserver.cue
addons/velaux/resources/parameter.cue
addons/velaux/resources/velaux.cue
addons/velaux/schemas/addon-uischema-velaux.yaml

add imagePullSecrets for addon velaux to pull images from private registry
When install addon velaux, user could specify customized image registry like this
`vela addon enable velaux serviceType=NodePort repo=acr.kubevela.net`
but usually, the private image registry needs authentication, and Pods need k8s secret to pull images from private image registry.
This patch allows user to  provide k8s secret and let velaux can be installed with private image registry as below:
`vela addon enable velaux serviceType=NodePort  repo=hub.myregistry.com imagePullSecrets="[\"regcred\"]" `
setup one private registry with Harbor, and assume the private Harbor registry is "hub.myregistry.com", username is "myname", password is "mypass", and secret name is "regcred"
1. install kebevela core and vela cli
2. …

Feat: add imagePullSecrets for addon velaux to pull images from private registry

---

addons/terraform-aws/definitions/terraform-aws-s3.yaml

AWS Terraform made a break change of setting acl for s3 in version 4.0 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#using-acl-policy-grants.
Fix https://github.com/oam-dev/kubevela/issues/3327
I have:

Fix the issue of provisioning aws s3

---

test/e2e-test/hack/addon-vela-test.sh

The CI test have been modified wrongly by #253 . The addon test is pull addon files from OSS addon registry. This pr fix this issue.
I have:

Fix:  fix  addon test ci 

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

- Removed `type` from outputs (https://github.com/oam-dev/terraform-controller/issues/274)
I have:

Upgrade terraform controller version to 0.4.3

---

.github/workflows/addon-test.yaml
addons/terraform/metadata.yaml

Terraform addons dependens on the version of kubevela to be upper
`v1.3.0-alpha.1`
I have:

Add system dependency for Terraform Addon

---

addons/terraform/metadata.yaml

The dependency mechanism of addons cloud not enable users to choose a
specified version of an addon
I have:

Remove dependency of addon terraform

---

addons/terraform-alibaba/schemas/component-uischema-terraform-alibaba.yaml
addons/terraform-aws/definitions/aws-provider.cue
addons/terraform-aws/schemas/component-uischema-terraform-aws.yaml
addons/terraform-azure/schemas/component-uischema-terraform-azure.yaml
addons/terraform-baidu/schemas/component-uischema-terraform-baidu.yaml
addons/terraform-gcp/schemas/component-uischema-terraform-gcp.yaml
addons/terraform-tencent/schemas/component-uischema-terraform-tencent.yaml
addons/terraform-ucloud/definitions/ucloud-provider.cue
addons/terraform-ucloud/schemas/component-uischema-terraform-ucloud.yaml
hack/addons/syn_addon_package.go

In VelaUX, hide Terraform Provider name (parameter.name) by creating a ui schema.
I have:

Hide Terraform provider name in VelaUX

---

addons/fluxcd/definitions/helm-release-def.yaml
addons/fluxcd/metadata.yaml

the reason is the status of helmRelease and helmRep is empty in the beginning.
Fix: https://github.com/kubevela/kubevela/issues/4051
I have:

Fix: helm component helm check incomplete error

---

hack/addons/syn_addon_package.go

load the system version requirements from the addon's meta.yaml, and then write this value as a value to ChartVersions.Metadata.Annotations, the corresponding key is "system".
Signed-off-by: HanMengnan <1448189829@qq.com>
hack/addons/syn_addon_package.go
Fixes #395
A `System` field is added to the metadata structure in `hack/addons/syn_ addon_ package.go` to record the system version requirements.
To adapt this feature, we need to add a `system` field to addon's `meta.yaml` file.
```yaml
name: example
version: 1.0.1
description: Extended workload to do continuous and progressive delivery
icon: https://raw.githubusercontent.com/fluxcd/flux/master/docs/_files/weave-flux.png
url: https://fluxcd.io
system:
vela: ">=v1.4.0-beta.2"
kubernetes: ">=1.20.0"
```
I have:

Feat: load the system version requirements from the addon's meta.yaml(#395)

---

hack/addons/syn_addon_package.go

addons dir support two versions of one same addon, eg: velaux and velaux-1.4
I have:

[Addon] CI support multi version of one addon

---

addons/chartmuseum/metadata.yaml
addons/chartmuseum/readme.md
addons/chartmuseum/resources/chartmuseum.cue
addons/chartmuseum/resources/gcs-credential.cue
addons/chartmuseum/resources/parameter.cue
addons/chartmuseum/template.yaml

Signed-off-by: Charlie Chiang <charlie_c_0129@outlook.com>
- Use vela built-in components. No dependencies required, which means we no longer need `fluxcd`. So users can easily install this in air-gapped environments.
- Add `image` parameter to make air-gapped installation possible.
- Support specifying existing PVC (in addition to auto-generated) to persist data.
- Delete some inappropriate parameters due to the usage of built-in traits.
Locally tested with some common parameters
A tutorial on air-gapped installation of addons is planned.
I have:

[Addon] Refactor: refactor chartmuseum addon with vela native components

---

addons/velaux/metadata.yaml
addons/velaux/resources/parameter.cue
addons/velaux/resources/velaux.cue
test/e2e-test/addon-test/main.go

Fixes kubevela/kubevela#4404
I have:

Fix: fix dex parameter in velaux addon

---

experimental/addons/azure-keyvault-csi/README.md
experimental/addons/azure-keyvault-csi/definitions/azure-keyvault-csi.cue
experimental/addons/azure-keyvault-csi/metadata.yaml
experimental/addons/azure-keyvault-csi/template.yaml

Add an azure-keyvault-csi trait addon.
As discussed with @FogDong & @wonderflow .
Used in our own AKS cluster to add secrets from an azure KeyVault which can then be successfully viewed with:
```
kubectl exec -n vela-test myapp-pod-name -- cat /mnt/secrets-store/my-secret
```
I have:
- `not updated docs as they are in main repo and this PR to experimental addon not yet accepted.  Example in README`
- `no update, new addon, v0.0.1`
- `experimental addon only`

[Addon] add the azure-keyvault-csi addon

---

addons/kube-state-metrics/metadata.yaml
addons/kube-state-metrics/parameter.cue
addons/kube-state-metrics/readme.md
addons/kube-state-metrics/resources/kube-state-metrics.cue
addons/kube-state-metrics/template.cue
addons/node-exporter/metadata.yaml
addons/node-exporter/parameter.cue
addons/node-exporter/readme.md
addons/node-exporter/resources/node-exporter.cue
addons/node-exporter/template.cue
test/e2e-test/addon-test/main.go

Add two metrics related addons:
- kube-state-metrics
- node-exporter
I have:

[Addon] metrics addons

---

addons/vela-prism/metadata.yaml
addons/vela-prism/parameter.cue
addons/vela-prism/resources/apiservices.cue
addons/vela-prism/resources/parameter.cue
addons/vela-prism/resources/privileges.cue
addons/vela-prism/resources/vela-prism.cue
addons/vela-prism/template.cue
addons/vela-prism/template.yaml

1. Upgrade to v1.5 to enable Grafana related apis.
2. Refactor to webservice based addon. Therefore, it does not relies on fluxcd anymore.
I have:

[Addon] Upgrade vela-prism to v1.5 and use webservice to replace helm

---

addons/fluxcd/resources/components/args.cue
addons/fluxcd/resources/components/helm-controller.cue
addons/fluxcd/resources/components/image-automation-controller.cue
addons/fluxcd/resources/components/image-reflector-controller.cue
addons/fluxcd/resources/components/kustomize-controller.cue
addons/fluxcd/resources/components/source-controller.cue
addons/fluxcd/resources/rbac/privileges.cue

Although the user seems can upgrade from old versions of fluxcd, and continue to use it, but the upgrade process is actually not completed. 
The reason why the user can continue to use fluxcd after upgrading is because the upgrade didn't even happen.
This pr makes the upgrade possible.
Reason:
```
Turn off leader-election, otherwise user cannot upgrade from previous versions.
Reason:
Atfer we upgrade fluxcd from 1.3.5 to 2.0.0, new deployment/pods are created.
The new ones will NOT be ready until the leader (previous pods) stepped down.
The previous leader will step down only when being GC'ed, but the GC will not happen
before the new pods are ready.
So the new pods will keep waiting for the previous leader to step down,
but the previous leader will never step down.
See? This is a …
```

[Addon] Fix: resolve fluxcd upgrade issues

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

There is a bug in Terraform controller v0.7.5. It won't destroy the cloud resources by default. If `Configuration.Spec.DeleteResource` set to false, it'll delete the resource which is not expected behavior.
I have:

[Addon] Bump terraform to 1.0.12

---

.github/workflows/addon-test.yaml
test/e2e-test/terraform-test/terraform_test.go
test/e2e-test/terraform-test/testdata/rds-database.yaml
test/e2e-test/terraform-test/testdata/rds-instance.yaml
test/e2e-test/terraform-test/testdata/redis.yaml

Add: rds, rds-instance, rds-database, redis definition test suite
I have:
I have:

[Addon] Add more regular test for terraform

---

experimental/addons/azure-keyvault-csi/definitions/azure-keyvault-csi.cue
experimental/addons/azure-keyvault-csi/metadata.yaml

Corrects an issue with azure-keyvault-csi trait where the patch to add the secrets-store volume does not correctly patch when there are existing volumeMounts, causing the component deployment to fail .
Fixes #462
With and without the change own cluster where problem was first detected.
I have:

[Addon] Fix for azure-keyvault-csi trait patch with other volumeMounts

---

experimental/addons/istio/template.yaml

When enabling the `istio` addon with `vela enable addon istio`
I was getting this error:
```sh
E0910 18:42:34.758361   48962 addon.go:1052] fail to create application: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot create the validation process context of app=addon-istio in namespace=vela-system: evaluate base template app=addon-istio in namespace=vela-system: invalid cue template of workload ns-istio-system after merge parameter and context: output: invalid operation null & [, ...{}] (mismatched types null and list) (and 2 more errors).
Error: fail to create application: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error …
```

[Addon] Fix istio addon k8s-objects

---

addons/terraform/metadata.yaml
addons/terraform/resources/parameter.cue
addons/terraform/resources/terraform-controller.cue

Allow user override helm chart values when enable terraform addon.
> *From Slack*
When we install the terraform-controller addon via vela cli some of the arguments are not set eg: --controller-namespace=vela-system
The args are part of the terraform-controller [chart](https://github.com/kubevela/terraform-controller/blob/4b5a5ebe47d0c362d8d178355d2838dcce3069e9/chart/templates/terraform_controller.yaml#L25), but the terraform-controller [addon](https://github.com/kubevela/catalog/blob/master/addons/terraform/resources/parameter.cue) is not setting any parameter in the [cue](https://github.com/kubevela/catalog/blob/master/addons/terraform/resources/parameter.cue) template. Is it intentional or missed to set the parameters?
Let's keep …

[Addon] Allow pass chart values for terraform addon

---

experimental/addons/azure-keyvault-csi/definitions/azure-keyvault-csi.cue
experimental/addons/azure-keyvault-csi/metadata.yaml

Allow the ability to mount secrets int `\mnt\secrets-store` with a different name than that of the key.
To use this, specify the optional `alias` value on a key.  If not given, the mounted name will be the same as the key name.
Used in local environment.
I have:

[Addon] Allow secret alias in azure-keyvault-csi trait

---

addons/fluxcd/definitions/kustomize.cue
addons/fluxcd/metadata.yaml

- Add `sourceName` optional field similar to #493 
Ref: https://github.com/kubevela/kubevela/issues/4820
1. I use the manifest in https://github.com/chengleqi/argocd-example-apps repo master branch `./nginx` path to generate a kustomize app named `test-kus-nginx`. It generated a kustomization named `test-kus-nginx` and a gitrepo named `test-kus-nginx`.
2. Then I create another kustomize app named `test-kus-nginx-sourcename` which `sourceName` field is `test-kus-nginx` indicated to the name of the gitrepo generated by the `test-kus-nginx` kustomize.
---
Check the state finally.
```shell
❯ flux get source git -A
NAMESPACE	NAME          	REVISION      	SUSPENDED	READY	MESSAGE
default  	test-kus-nginx	master/92ce5d2	False    	True 	stored artifact for revision …
```

[Addon] Add optional field sourceName for kustomize

---

addons/loki/metadata.yaml
addons/loki/parameter.cue

Signed-off-by: Xiadong Zhu <zhuxiadong.zxd@alibaba-inc.com>
Vector supports sending data to Loki via its native snappy-compressed protobuf protocol from v0.25.0 releasing.
We should change the image version of Vector in Loki addon to enable that feature.
Code has been tested with `vela addon enable <local addon path>`
I have:

[Addon] loki: upgrade vector to 0.25.2

---

addons/o11y-definitions/definitions/install-kubernetes-api-datasource.cue
addons/o11y-definitions/metadata.yaml

In addon `o11y-definitions`, there is a workflowstep definition called `install-kubernetes-api-datasource` which install Kubernetes apiserver endpoint as one type of datasource to Grafana.
The underlying logic is to create a ServiceAccount and get the token for it. Then the token will be embedded as the authorization header in Grafana Datasource for access.
In k8s 1.24+, the token will not be generated automatically for the ServiceAccount [1]. This PR supports manually create secret for getting the token while keeping compatibility for the old version k8s.
Reference:
1. https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount
I have:
If this pr wants to promote an …

[Addon]: add support for k8s 1.24+ for install k8s api for o11y-definitions

---

experimental/addons/istio/definitions/canary-rollout-wf-def.yaml
experimental/addons/istio/definitions/rollback-wf-def.yaml
experimental/addons/istio/definitions/traffic-trait-def.yaml

Signed-off-by: suwanliang_yewu <suwanliang_yewu@cmss.chinamobile.com>
modify the destinationrules's label `app.oam.dev/revision` to `service.istio.io/canonical-name`,because the lable `app.oam.dev/revision` belongs to deployment, the pod doesn't have the label.
following [istio](https://www.bookstack.cn/read/kubevela.io-1.1-zh/3aecdfaa8a4c3bf2.md)
I have:

[Addon istio]Modify the label of destinationrules

---

addons/flink-kubernetes-operator/metadata.yaml
addons/flink-kubernetes-operator/template.cue
test/e2e-test/addon-test/PENDING

changed the version from 1.1.0 to 1.3.0
debugged the addon in my local, installed offline:
```
vela addon enable /root/.vela/addons/flink-kubernetes-operator
```
show the status:
```
vela addon status flink-kubernetes-operator
```
the result：
```
flink-kubernetes-operator: enabled (1.3.0)
==> Installed Clusters
[local]
==> Registry Name
local
```
I have:

[Addon] Fix the version issue of flink-kubernetes-operator

---

examples/cronhpa/cronhpa-sample.yaml
experimental/addons/cronhpa/README.md
experimental/addons/cronhpa/definitions/cronhpa.cue
experimental/addons/cronhpa/metadata.yaml
experimental/addons/cronhpa/parameter.cue
experimental/addons/cronhpa/resources/component/cronController.cue
experimental/addons/cronhpa/resources/crd/cronhpa.cue
experimental/addons/cronhpa/resources/rbac/controller-clusterrole.cue
experimental/addons/cronhpa/resources/rbac/controller-rolebinding.cue
experimental/addons/cronhpa/schemas/cronhpaschema.yaml
experimental/addons/cronhpa/template.cue

Signed-off-by: StevenLeiZhang <zhangleiic@163.com>
fix:#573
build one addon based on https://github.com/AliyunContainerService/kubernetes-cronhpa-controller
After addon installed, one new Trait is exposed, which is named "cronhpa". User could use it to set cronhpa for Component.
test it locally.
1. install it
```
cd experimental/addons/cronhpa
vale addon enable ./
```
2. wait for it is up
3.run test Application
```
cd examples/cronhpa
kubectl apply -f cronhpa-sample.yaml
```
4. check the pod amount of helloworld Application.
It will scale up and down every 30s.
I have:

Feat: need support cron hpa

---

test/e2e-test/terraform-test/testdata/security-group.yaml

Fix security group regular check. Now it will stuck because namespace `prod` doesn't exist.
I have:

Fix: regular check security group

---

addons/fluxcd/metadata.yaml
addons/fluxcd/parameter.cue
addons/fluxcd/resources/components/helm-controller.cue
addons/fluxcd/resources/components/image-automation-controller.cue
addons/fluxcd/resources/components/image-reflector-controller.cue
addons/fluxcd/resources/components/kustomize-controller.cue
addons/fluxcd/resources/components/source-controller.cue

Add advanced parameters to support [options](https://fluxcd.io/flux/components/helm/options/) for fluxcd's controller.
Example:
``` vela addon enable fluxcd clusters="{local}" helmControllerOptions="{--no-cross-namespace-refs,--concurrent=5}"```
I have tested on my cluster. 
I have:

[Addon]feat: add advanced options for fluxcd controllers

---

examples/spark-kubernetes-operator/sparkapp-py.yaml
examples/spark-kubernetes-operator/sparkapp.yaml
experimental/addons/spark-kubernetes-operator/README.md
experimental/addons/spark-kubernetes-operator/definitions/spark-application.cue
experimental/addons/spark-kubernetes-operator/definitions/spark-workload.cue
experimental/addons/spark-kubernetes-operator/metadata.yaml
experimental/addons/spark-kubernetes-operator/parameter.cue
experimental/addons/spark-kubernetes-operator/template.cue

Signed-off-by: yanghua <yanghua1127@gmail.com>
I have:

[Addon #603] Add Apache Spark as a experimental addon

---

addons/loki/definitions/stdout-logs.cue
addons/loki/metadata.yaml
addons/loki/parameter.cue
addons/loki/resources/agent-promtail.cue
addons/loki/resources/agent-vector.cue
addons/loki/resources/agent.cue
addons/loki/resources/loki.cue
addons/loki/template.cue
addons/prometheus-server/metadata.yaml
addons/prometheus-server/parameter.cue
addons/prometheus-server/resources/prometheus-config.cue
addons/prometheus-server/resources/prometheus-server.cue

1. Support configuring scrapeInterval.
2. The resource configuration is only applied for prometheus-server container. The thanos sidecar container will not be enforced by that. (Solves #555)
1. Support agentOnly parameter to skip the installation of loki.
2. Support lokiURL parameter to set the endpoint that agent needs to sink to.
3. The default agent mode is changed from "" (no agent install) to "vector".
I have:

[Addon] enhance loki & prom addon

---

addons/kruise-rollout/definitions/rolling-release.cue
addons/kruise-rollout/metadata.yaml
addons/kruise-rollout/schemas/workflowstep-uischema-canary-deploy.yaml
addons/kruise-rollout/template.cue
examples/kruise/rollout/rollout-with-workflow-v2.yaml

The webhook of the rollout controller intercepts all updating requests of deployment. However, if the Kruise Rollout pod crashes, it blocks all deployment operations. This PR addresses the issue by allowing the rollout controller to focus only on deployments that contain the krusie-rollout.oam.dev/webhook label. Additionally, if the workload uses the canary-deploy step, Vela will patch this label on it automatically.
I have:

Fix: add object select label for workload

---

addons/cert-manager/README.md
addons/cert-manager/metadata.yaml
addons/cert-manager/parameter.cue
addons/cert-manager/resources/alidns-dns01.cue
addons/cert-manager/template.cue

Add alidns webhook support to cert-manager
I have:

[Addon]: add alidns support to cert-manager

---

addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue

fixes https://github.com/kubevela/workflow/issues/169
The version 0.6.0 comes with the latest changes to the api calls to k8s upstream and fixes the issue mentioned above
I have:
- [ x] Title of the PR starts with type (e.g. `[Addon]` , `[example]` or `[Doc]`).
- [ x] Update addon should modify the `version` in `metadata.yaml` to generate a new version.

[Addon] fix: Update vela-workflow

---

addons/kube-state-metrics/metadata.yaml
addons/kube-state-metrics/resources/kube-state-metrics.cue
addons/victoria-metric/README.md
addons/victoria-metric/metadata.yaml
addons/victoria-metric/parameter.cue
addons/victoria-metric/resources/namespace.cue
addons/victoria-metric/resources/vm-agent.cue
addons/victoria-metric/resources/vm-cluster.cue
addons/victoria-metric/schemas/schema.yaml
addons/victoria-metric/template.cue
test/e2e-test/addon-test/PENDING
test/e2e-test/addon-test/main.go

Feat: Add the VM as an observability addon

---

experimental/addons/datadog/README.md
experimental/addons/datadog/definitions/datadog.cue
experimental/addons/datadog/metadata.yaml
experimental/addons/datadog/template.yaml

Adding a trait to sets up the annotations and environment variables to assist a webservice 
or cron-task component to have correct collection of logs and apm stats by a datadog agent
installed on the host nodes.
Add datadog experimental trait
Used on my own cluster.
I have:
Doc update not yet performed.  I'm happy to do that before PR merged, but need some assistance - The PR template mentions kubevela.io, but is it now kubevela.github.io? I also can't really figure out how the source maps to the published site. Happy to raise a PR for docs too, but I'm going to need some pointers.

[Addon] Datadog trait

---

experimental/addons/azure-keyvault-csi/definitions/azure-keyvault-csi.cue
experimental/addons/azure-keyvault-csi/metadata.yaml

An update to the experimental azure-keyvault-csi trait (of which I am the author), so that it also supports being used with `cronjobs.batch` object/`cron-task` component.
Used in my own cluster
I have:

[Addon] add cronjob support to azure-keyvault-csi trait

---

experimental/addons/datadog/definitions/datadog.cue
experimental/addons/datadog/metadata.yaml

- syntax error bugfixes
- add the ability to specify mounted volume name
- add the ability to auto-map dependecies using `DD_TRACE_SERVICE_MAPPING` env var
Used on own cluster.
I have:

[Addon] update datadog trait

---

addons/chartmuseum/metadata.yaml
addons/chartmuseum/readme.md
addons/chartmuseum/resources/chartmuseum.cue
addons/chartmuseum/resources/parameter.cue

Add an option to change the default configuration of the default cache refresh interval, the default is causing us to have stale charts and failing releases.
I have:

[Addon] Chartmuseum add a cache refresh option #751

---

experimental/addons/azure-keyvault-csi/definitions/azure-keyvault-csi.cue
experimental/addons/azure-keyvault-csi/metadata.yaml

Fixes a typo preventing the addon being enabled.
Used locally.
I have:

[Addon] fix azure-keyvault-csi trait

---

experimental/addons/datadog/definitions/datadog.cue
experimental/addons/datadog/metadata.yaml

Works around [kubevela issue #6510](https://github.com/kubevela/kubevela/issues/6510) (and also fix a typo)
Used on own clusters
I have:

[Addon] Fix datadog trait with workaround for kubevela issue #6510

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/definitions/kustomize.cue
addons/fluxcd/metadata.yaml
addons/fluxcd/resources/components/helm-controller.cue
addons/fluxcd/resources/components/image-automation-controller.cue
addons/fluxcd/resources/components/image-reflector-controller.cue
addons/fluxcd/resources/components/kustomize-controller.cue
addons/fluxcd/resources/components/source-controller.cue
addons/fluxcd/resources/crds/bucket.cue
addons/fluxcd/resources/crds/git-repo.cue
addons/fluxcd/resources/crds/helm-chart.cue
addons/fluxcd/resources/crds/helm-release.cue
addons/fluxcd/resources/crds/helm-repo.cue
addons/fluxcd/resources/crds/image-policy.cue
addons/fluxcd/resources/crds/image-repo.cue
addons/fluxcd/resources/crds/image-update-automation.cue
addons/fluxcd/resources/crds/kustomize.cue
addons/fluxcd/resources/crds/oci-repo-new.cue

Updates the FluxCD addon to Flux2.
Fixes #705 
The addon has been tested in my local Kubevela instance.
I have:

[Addon] Update to Flux2

---

.github/CODEOWNERS

Adding Fog, Daniel and Anoop to codeowners for more coverage on PRs

Chore: Add Fog, Daniel and Anoop to codeowners

---

addons/flink-kubernetes-operator/metadata.yaml
addons/flink-kubernetes-operator/parameter.cue
addons/flink-kubernetes-operator/template.cue

Hello Everyone 👋 Flink people seem to have removed old versions of the operator from their helm chart repository. The oldest version that is still in existence is 1.7.0. I've removed the hardcoded version reference, and allowed for parameterising the version going forward.
I have:

[Addon] fix: removing hardcoded non-existing flink operator helm chart, and allowing for parameterising operator version

---

experimental/addons/datadog/definitions/datadog.cue
experimental/addons/datadog/metadata.yaml

… when serviceName differs from component name
This fixes the logging annotation added by this trait so that it uses the component name 
and not any serviceName alias specified.  This is to give correct operation of the 
logging source functionality.
Used on own cluster
I have:
(N/A - this addon to remain alpha)

[Addon] Fix for datadog trait logging source setup 

---

examples/crossplane-azure/resourceGroup.yaml
examples/crossplane-azure/storageAccount.yaml
examples/crossplane-azure/virtualNetwork.yaml
experimental/addons/crossplane-azure/README.md
experimental/addons/crossplane-azure/definitions/azure-rg.cue
experimental/addons/crossplane-azure/definitions/azure-storage-account.cue
experimental/addons/crossplane-azure/definitions/azure-vnet.cue
experimental/addons/crossplane-azure/definitions/crossplane-azure.cue
experimental/addons/crossplane-azure/metadata.yaml
experimental/addons/crossplane-azure/resources/provider.yaml
experimental/addons/crossplane-azure/template.yaml
test/e2e-test/hack/addon-vela-test.sh

[Addon] Add Crossplane-Azure Addon
This PR adds the **Crossplane-Azure** addon to the KubeVela catalog as an experimental addon. The addon facilitates the provisioning of Azure resources like Resource Groups, Virtual Networks, and Storage Accounts via Crossplane on KubeVela.
- It contains necessary components, including CUE files and provider configurations, as well as a detailed `README.md` file explaining the usage, installation, and authentication setup. 
- Additionally, examples are provided in the `examples` directory, showing the Azure Resource Group, Virtual Network, and Storage Account creation.
I have copied the entire addon directory `crossplane-azure`, which contains the CUE files and provider files. I tested this locally by using the following command:
```bash
vela addon …
```

[Addon] Add Crossplane Azure Addon for provisioning Cloud Resources on Azure

---

experimental/addons/azure-keyvault-csi/definitions/azure-keyvault-csi.cue
experimental/addons/azure-keyvault-csi/metadata.yaml
experimental/addons/datadog/definitions/datadog.cue
experimental/addons/datadog/metadata.yaml

Added support for statefulset on the datadog and keyvault csi driver by updating the "appliesToWorkloads" field.
tested locally with the "vela dry-run -d kubevela -f statefulset-app.yml --offline" The output yaml file had a statefulset definition with the information from datadog and kv csi driver traits.
I have:

[Addon] add statefulset to datadog and keyvault

---

addons/vela-core-shard-manager/metadata.yaml
addons/vela-core-shard-manager/template.cue

In KubeVela v1.10, the package [k8s.io/apimachinery](http://k8s.io/apimachinery) was upgraded from v0.26.3 to v0.29.2. We've observed that this upgrade causes KubeVela to only load the default groups ("[core.oam.dev](http://core.oam.dev/)" and "").
As a result, when using resources in ref-objects with a group other than the default, we now need to explicitly specify the group in the YAML. Specifically, we noticed that the vela-core-shard-manager add-on deployment is failing because the group needs to be specified. In this case, the apps group should be explicitly added for the deployment resource.
Fixes #6719
We added the group in resource of the addon application and verified it deployed successfully.
I have:
If this pr wants to promote an experimental addon to verified, you must check …

[Addon]: added group in vela-core-shard-manager addon yaml

---

addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue

Changing the vela-workflow addon version to use v0.6.2 by default
I have:
---
Updated the default vela-workflow addon version to v0.6.2.

Chore: Update the vela-workflow addon version to v0.6.2
