kubevela/catalog

traits/experimental/servicetrait/Dockerfile
traits/experimental/servicetrait/README.md
traits/experimental/servicetrait/api/v1alpha2/servicetrait_types.go
traits/experimental/servicetrait/config/samples/sample_application_config.yaml
traits/experimental/servicetrait/config/samples/sample_component.yaml
traits/experimental/servicetrait/config/samples/sample_workload_definition.yaml
traits/experimental/servicetrait/controllers/helper.go
traits/experimental/servicetrait/controllers/service.go
traits/experimental/servicetrait/controllers/servicetrait_controller.go
traits/experimental/servicetrait/controllers/servicetrait_controller_helper.go
traits/experimental/servicetrait/go.mod
traits/experimental/servicetrait/go.sum

Add support for K8S native Deployment and Statefulset
Add support for OAM ContainerizedWorkload
update readme
Refer to [README](https://github.com/oam-dev/catalog/compare/master...My-pleasure:servicetrait?expand=1#diff-52e835ed2370e82c27b68410caf831e2) please
I have:

[Trait] Refine ServiceTrait and update readme

---

workloads/advancedstatefulset/README.md
workloads/advancedstatefulset/sampeapp.yaml
workloads/advancedstatefulset/sample-asts-component.yaml
workloads/advancedstatefulset/workloadDefinition.yaml
workloads/cloneset/README.md
workloads/cloneset/sampeapp.yaml
workloads/cloneset/sample-cls-component.yaml
workloads/cloneset/workloadDefinition.yaml

Add example intro docs and sample yaml files for Kruise workloads
- CloneSet
- AdvancedStatefulSet
These docs show how to use Kruise workloads in OAM runtime.
Only doc and yaml files.
I have:

[Workload] Add example docs and sample YAML files for Kruise workloads

---

workloads/README.md

Add more workload example in workload README
Just documentation.
I have:

Add more workload example in workload README

---

traits/hpatrait/config/default/kustomization.yaml
traits/hpatrait/config/oam/kustomization.yaml
traits/hpatrait/config/oam/trait_definition.yaml
traits/ingresstrait/config/default/kustomization.yaml
traits/ingresstrait/config/oam/kustomization.yaml
traits/ingresstrait/config/oam/trait_definition.yaml
traits/servicetrait/config/default/kustomization.yaml
traits/servicetrait/config/oam/kustomization.yaml
traits/servicetrait/config/oam/trait_definition.yaml

Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Add TraitDefinition for hpatrait/ingresstrait/servicetrait traits.
None, just add yamls.
I have:

[Trait]Add TraitDefinition for hpatrait/ingresstrait/servicetrait

---

traits/README.md
traits/hpatrait/controllers/hpa_trait_test.go
traits/hpatrait/controllers/suite_test.go
traits/hpatrait/test/hpa_trait_controller_test.go
traits/hpatrait/test/suite_test.go

- Add e2e test for hpatrait covering support for ContainerizedWorkload/Deployment/Statefulset;
- Update catalog/traits README.md;
Before run test, please follow hpatrait/README.md to set up local test env.
I have:

[Trait] Add e2e test for hpatrait

---

workloads/statefulset/README.md

update docs: [workloads/statefulset](/oam-dev/catalog/workloads/statefulset/README.md)
add `ClusterRoleBinding`
I have:

[Workload]fix docs of workloads/statefulset

---

traits/ingresstrait/README.md

The README is verbose and needs revise.

---

traits/hpatrait/Makefile
traits/hpatrait/config/rbac/role.yaml
traits/hpatrait/controllers/horizontalpodautoscalertrait_controller.go
traits/hpatrait/controllers/horizontalpodautoscalertrait_controller_test.go

Add unit test for hpatrait;
Add rbac config for hpatrait;
coverage: 65.5% of statements of controllers pkg
I have:

[Trait] add unit test for hpatrait

---

traits/hpatrait/config/oam/trait_definition.yaml
traits/ingresstrait/config/oam/trait_definition.yaml
traits/metrichpatrait/README.md
traits/metrichpatrait/api/v1alpha2/metrichpatrait_types.go
traits/metrichpatrait/config/crd/bases/extend.oam.dev_metrichpatraits.yaml
traits/metrichpatrait/config/oam/trait_definition.yaml
traits/metrichpatrait/controllers/helper.go
traits/metrichpatrait/controllers/metrichpatrait_controller.go
traits/serviceexpose/config/oam/trait_definition.yaml
traits/simplerollouttrait/README.md
traits/simplerollouttrait/config/oam/trait_definition.yaml

- complete MetricHPATrait
- Enable external Prometheus server 
- Add Garbage Collection of MetricHPATrait
- add workloadRef field in trait definitions
- update README.md of MetricHPATrait and SimpleRolloutTrait
unit tests remain to add
I have:

[Trait] complete MetricHPATrait and update README.md

---

registry/advancedstatefulset.yaml
registry/deployment.yaml

Enable `vela cap` to install all extended capabilities
I have:

Add extended workload types to registry folder

---

applications/knative/README.md
applications/knative/application-v1.yaml
applications/knative/workloaddefinition-knative-serving.cue
applications/knative/workloaddefinition-knative-serving.yaml

Part 1: Deploy application with Knative Serving Workload, then interact with it using cURL requests

Integrate Knative (part 1)

---

Makefile
traits/routetrait/Makefile
traits/routetrait/controllers/route_controller_test.go
traits/routetrait/controllers/suite_test.go
traits/routetrait/go.mod

delete route test case witch should rely on podspecworkload controller

delete route test related podspecworkload

---

.github/workflows/registry.yaml
traits/autoscalertrait/Makefile
traits/metricstrait/Dockerfile
traits/metricstrait/Makefile
traits/routetrait/Makefile
workloads/podspecworkload/Dockerfile
workloads/podspecworkload/Makefile

add docker image push workflow yaml

add registry yaml for docker image 

---

registry/advancedstatefulset.yaml
registry/autoscale.yaml
registry/deployment.yaml
registry/for-loop.yaml
registry/ingress.yaml
registry/initcontainer.yaml
registry/kautoscale.yaml
registry/kubewatch.yaml
registry/metrics.yaml
registry/node-affinity.yaml
registry/openfaas.yaml
registry/patch-replica.yaml
registry/podenv.yaml
registry/rollout.yaml
registry/route.yaml
registry/virtualgroup.yaml

set registry definition namespace  vela-system

add definition namespace

---

registry/autoscale.yaml
registry/metrics.yaml
registry/route.yaml
traits/autoscalertrait/main.go
traits/metricstrait/charts/metricstrait/values.yaml
traits/metricstrait/main.go
traits/routetrait/main.go

our registry definition yaml are too old, fix them and add scheme for 3 controllers

fix old registry yaml and scheme bug

---

registry/kubewatch.yaml
registry/rollout.yaml
traits/metricstrait/charts/metricstrait/templates/metricstrait_controller.yaml

disable webhook and fix several td yaml

Disable webhook and fix several td yaml

---

README.md
traits/README.md
traits/autoscalertrait/README.md
traits/metricstrait/README.md
traits/routetrait/README.md
workloads/README.md

add docs for catalog

---

applications/crossplane/README.md

Update the link to cloud service

---

applications/crossplane/componentdefinition-oss.cue
applications/crossplane/componentdefinition-oss.yaml
applications/crossplane/componentdefinition-rds.cue
applications/crossplane/componentdefinition-rds.yaml
applications/crossplane/traitdefinition-service-binding.cue
applications/crossplane/traitdefinition-service-binding.yaml

Added parameter comments for ComponentDefinition alibaba-oss
alibaba-rds and TraitDefinition service-binding
I have:

Add parameters comments for crossplane definitions

---

applications/crossplane/componentdefinition-oss.yaml

modified description field description
Fixes #104 
I have:

Fix alicloud oss resource case description field incorrect

---

registry/route.yaml

[Trait] Remove route trait's dependency on ingress.

---

registry/dynamic-sa.yaml
registry/kruise-sts.yaml

[Workload][Trait] Rename to align metadata and filename

---

addons/example/definitions/helm.yaml
addons/example/metadata.yaml
addons/example/readme.md
addons/example/template/deploy.cue
addons/example/template/parameter.cue

Structure:
- definitions/: contains the x-definitions yaml/cue files
- template/: contains the CUE template files, and a special `parameter.cue` to expose parameters. It could also be yaml file if not using any parameters.
- metadata.yaml: special metadata file
- readme.md: README file

Feat: new addon structure example

---

addons/example/template/configmap.cue

remote key which is reserved as component name
I have:

update cue template

---

addons/example/resources/configmap.cue

Fix addon example

---

addons/fluxcd/metadata.yaml
addons/istio/metadata.yaml
addons/kruise/metadata.yaml

This pr should be blocked until https://github.com/oam-dev/kubevela/issues/2562 been fixed
I have:

Fix: enable runtime and other description fixed

---

addons/example/resources/service/source-controller.yaml

fix namespace, make this addon not running
I have:

fix example addon

---

addons/fluxcd/definitions/json-patch.yaml
addons/fluxcd/definitions/kustomize-patch.yaml
addons/fluxcd/definitions/strategy-merge.yaml
addons/fluxcd/metadata.yaml
addons/fluxcd/template.yaml

add need-namespace

---

addons/istio/template.yaml
addons/kruise/template.yaml
addons/observability/template.yaml
addons/terraform/template.yaml

remove depends-on-app workflow step to avoid conflict.
I have:

fix depends-on-app block

---

addons/example/metadata.yaml

remove example dependency

---

addons/terraform-provider-alibaba/resources/alibaba-account-creds.cue
addons/terraform-provider-alibaba/resources/parameter.cue

It make no sense to expose this parameter to UI users
I have:

Remove ALICLOUD_SECURITY_TOKEN from terraform provider-alibaba

---

addons/observability/resources/prometheus-server.cue

Fixed the wrong format of the values of the chart from promethues component
I have:

Fix values for installing promethues component

---

addons/fluxcd/schemas/component-uischema-helm.yaml

add helm definition UI  schema 
I have:

helm schema

---

addons/observability/resources/parameter.cue

Made a mistake to have parameters.cue deelted, took it back
I have:

Revert parameters of observability

---

addons/terraform/template.yaml

- Clean RBAC
- Generate Job/Pod/ConfigMap/Secret in the namespace of a Configuration
- Fix: The secret generated by Terraform won't regenerate after it's manually deleted
- Fix status ProvisioningAndChecking
- The Kubernetes backend should keep consistent
- Override Region of a provider in Configuration
- Set region to spec.region
I have:

Fix: upgrade terraform controller to v0.2.10 (#2827)

---

addons/terraform/template.yaml

- Add a label to mark the secret https://github.com/oam-dev/terraform-controller/pull/187
I have:

Fix: upgrade terraform controller to v0.2.11

---

addons/terraform-alibaba/definitions/terraform-alibaba-ask.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-oss.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-rds.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-redis.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-sls-project.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-sls-store.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-vpc.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-vswitch.yaml

Added more Terraform ComponentDefinitions for Alibaba Cloud, and
renamed ALICLOUD_REGION to REGION
I have:

Add more alibaba cloud definitions and rename ALICLOUD_REGION

---

addons/fluxcd/readme.md
addons/velaux/metadata.yaml
addons/velaux/readme.md
addons/velaux/readme_cn.md
addons/velaux/resources/apiserver.cue
addons/velaux/resources/parameter.cue
addons/velaux/resources/velaux.cue
addons/velaux/schemas/component-uischema-k8s-objects.yaml
addons/velaux/schemas/component-uischema-webservice.yaml
addons/velaux/template.yaml

The velaux addon includes application、uischema and velaql.

Feat: add velaux addon

---

addons/terraform-alibaba/definitions/terraform-alibaba-oss.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-rds.yaml

Hide three fields for Alibaba RDS definition

---

addons/velaux/resources/apiserver.cue
addons/velaux/resources/parameter.cue
addons/velaux/resources/velaux.cue
addons/velaux/resources/views.cue

Feat: add velaql views to velaux addon

---

addons/fluxcd/schemas/component-uischema-helm.yaml
addons/terraform-alibaba/schemas/component-uischema-alibaba-rds.yaml
addons/velaux/resources/apiserver.cue
addons/velaux/resources/parameter.cue
addons/velaux/schemas/addon-uischema-velaux.yaml
addons/velaux/schemas/component-uischema-task.yaml
addons/velaux/schemas/component-uischema-webservice.yaml

Feat: add uischema for velaux addon

---

.github/workflows/addon.yaml

Signed-off-by: qiaozp <chivalry.pp@gmail.com>
I have:

[Addon] automatically sync catalog addons to OSS

---

.github/workflows/addon.yaml

fix addon script region

---

.github/workflows/addon.yaml

Signed-off-by: qiaozp <chivalry.pp@gmail.com>
I have:

Fix addon sync script

---

addons/velaux/resources/apiserver.cue
addons/velaux/resources/parameter.cue
addons/velaux/resources/velaux.cue
addons/velaux/resources/views.cue

Feat: fix velaux addon

---

addons/velaux/resources/parameter.cue

- fix velaux parameter
I have:

Fix velaux addon parameter

---

addons/velaux/resources/velaux.cue

Signed-off-by: wangyike <wangyike_wyk@163.com>
I have:

Fix: small fix to vela-ux

---

addons/observability/metadata.yaml

Revert "Observability add-on needs to customize runtime"

---

addons/velaux/resources/parameter.cue

Fix: change velaux default version

---

addons/velaux/resources/parameter.cue

Fix: the repo parameter is not required.

---

addons/velaux/resources/apiserver.cue
addons/velaux/resources/parameter.cue
addons/velaux/resources/velaux.cue

Signed-off-by: 流鑫 <songyang.song@alibaba-inc.com>
I have:

Fix: fix velaux addon

---

addons/velaux/resources/apiserver.cue

Signed-off-by: 流鑫 <songyang.song@alibaba-inc.com>
I have:

Fix: fix image in velaux addon

---

addons/ocm-cluster-manager/template.yaml

[Workload] Fix ocm cluster management addon bug

---

addons/ocm-cluster-manager/readme.md

> Signed-off-by: yue9944882 <291271447@qq.com>

Doc: Clarifying addon ocm-cluster-manager 

---

addons/fluxcd/definitions/helm-release-def.yaml
addons/fluxcd/schemas/component-uischema-helm.yaml

fix bugs of componentDefinition
I have:

Fix: helm definition

---

addons/velaux/resources/views.cue

Fix: fix pod-view

---

addons/velaux/schemas/workflowstep-uischema-notification.yaml

Feat: add notification ui schema
I have:

Feat: add notification ui schema

---

addons/fluxcd/schemas/component-uischema-helm.yaml

Fix: helm componet schema

---

.github/CODEOWNERS

add addon code owners
I have:
/cc @Somefive @zzxwill @wangyikewxgm @barnettZQG @wonderflow

Feat: add addon code owners

---

addons/fluxcd/resources/crds/image-policy.yaml
addons/fluxcd/resources/crds/image-repo.yaml
addons/fluxcd/resources/crds/image-update-automation.yaml
addons/fluxcd/resources/deployment/image-automation-controller.yaml
addons/fluxcd/resources/deployment/image-reflector-controller.yaml
addons/fluxcd/resources/rbac/binding-crd-controller.yaml
addons/fluxcd/resources/rbac/image-automation-controller.yaml
addons/fluxcd/resources/rbac/image-reflector-controller.yaml
addons/terraform/metadata.yaml

Signed-off-by: wangyike <wangyike_wyk@163.com>
I have:

Fix: revert fluxcd image policy back and terraform invisible false

---

addons/terraform/template.yaml

* Validate Alibaba credentials ak/sk/ststoken by @zzxwill in https://github.com/oam-dev/terraform-controller/pull/195
* Fix unproper clusterrolebinding settings by @wangwang in https://github.com/oam-dev/terraform-controller/pull/197
I have:

Bump terraform addon to v0.2.14

---

addons/velaux/resources/parameter.cue

Feat: change velaux version

---

addons/terraform-alibaba/resources/parameter.cue

This settings will help guide users to set parameters for
Addon Terraform Alibaba
I have:

Add parameters descriptions for `Addon Terraform Alibaba

---

.github/workflows/addon.yaml

Signed-off-by: qiaozp <chivalry.pp@gmail.com>
**Please hold this PR until code ready**
I have:

sync experimental addons to bucket

---

addons/README.md
experimental/addons/README.md
test/e2e-test/hack/addon-vela-test.sh

Signed-off-by: wangyike <wangyike_wyk@163.com>
I have:

Feat: addon readme

---

test/e2e-test/hack/addon-vela-test.sh

Signed-off-by: wangyike <wangyike_wyk@163.com>
I have:

Fix:  fix error ci

---

addons/velaux/resources/parameter.cue

Feat: change velaux version is 1.2.0-rc.1

---

addons/velaux/resources/views.cue

Support [Feat: support logs for velaql #3011](https://github.com/oam-dev/kubevela/pull/3011).
I have:

Feat: add collect-logs for velaql

---

addons/velaux/schemas/workflowstep-uischema-notification.yaml

Feat: optimize the uischema for notification workflowstep

---

addons/velaux/resources/parameter.cue
addons/velaux/schemas/component-uischema-webservice.yaml
addons/velaux/schemas/workflowstep-uischema-deploy2env.yaml
addons/velaux/schemas/workflowstep-uischema-webhook.yaml

Feat: upgrade velaux to 1.2.0-rc.2

---

experimental/addons/observability/resources/parameter.cue
experimental/addons/observability/resources/prometheus-server.cue

Signed-off-by: songyang.song <songyang.song@alibaba-inc.com>
I have:

Fix: set the unit for the storage size of prometheus

---

addons/terraform-alibaba/definitions/terraform-alibaba-eip.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-oss.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-rds.yaml
addons/terraform-aws/definitions/terraform-aws-s3.yaml
addons/terraform-azure/definitions/terraform-azure-database-mariadb.yaml

Upgrade API version from v1alph2 to v1beta1
I have:

Upgrade API version for cloud resources

---

addons/velaux/resources/parameter.cue

Feat: update velaux version to 1.2.0

---

addons/terraform-alibaba/definitions/terraform-alibaba-redis.yaml

Fixed the configuration setting for ComponentDefinition of Alibaba
Cloud Redis
I have:

Fix Redis ComponentDefinition

---

addons/velaux/resources/parameter.cue

Feat: change velaux version to 1.2.1

---

addons/terraform-alibaba/definitions/terraform-alibaba-oss.yaml
addons/terraform-azure/definitions/terraform-azure-database-mariadb.yaml

Added descriptions for variables and outputs for Terraform
typed ComponentDefinition
I have:

Add descriptions for Terraform typed ComponentDefinition

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

Upgraded the version of Addon terraform, and also added compatability
specification
I have:

Upgrade Terraform version and add compatibility specification

---

addons/terraform-tencent/definitions/terraform-tencent-vpc.yaml
addons/terraform-tencent/metadata.yaml
addons/terraform-tencent/readme.md
addons/terraform-tencent/resources/parameter.cue
addons/terraform-tencent/resources/tencent-account-creds.cue
addons/terraform-tencent/resources/tencent.cue
addons/terraform-tencent/template.yaml

Tencent Cloud has been supported in Terraform Controller by a developer.
So import it to the registry to work as the provider for Tencent Cloud
I have:

Add Terraform provider addon terraform-tentcent

---

addons/velaux/schemas/component-uischema-webservice.yaml

update velaux UIschema

---

addons/fluxcd/resources/deployment/source-controller.yaml

fluxcd cannot support customize cluster domain
I have:

Fix: fluxcd cannot support customize cluster domain

---

addons/velaux/resources/parameter.cue
addons/velaux/schemas/addon-uischema-velaux.yaml

Feat: change the velaux version to v1.2.2

---

addons/terraform/metadata.yaml
addons/terraform/resources/terraform-controller.cue

Detailed updates: https://github.com/oam-dev/terraform-controller/releases/tag/v0.3.4
I have:

Upgrade the version for Addon Terraform

---

addons/terraform-azure/definitions/terraform-azure-storage-account.yaml

Added one more cloud resource
I have:

Add Azure Storage account

---

addons/terraform-tencent/definitions/terraform-tencent-vpc.yaml

Added type of several variables for Tencent Cloud VPC
I have:

Add type for several variables of Tencent Cloud VPC

---

addons/terraform-tencent/definitions/terraform-tencent-subnet.yaml

Added one more cloud resoruce: Tencent Cloud Subnet
I have:

Add Tencent Cloud Subnet

---

addons/terraform-alibaba/definitions/terraform-alibaba-mse.yaml

Added ComponentDefinition alibaba-mse for Alibaba
Cloud MSE
I have:

Add one more cloud resource: Alibaba Cloud MSE

---

addons/terraform-alibaba/definitions/terraform-alibaba-mongodb.yaml

Added one more cloud resource
I have:

Add Alibaba Cloud MongoDB

---

addons/terraform-alibaba/definitions/terraform-alibaba-rocketmq.yaml

Added ComponentDefinition for Alibaba` Cloud RocketMQ
I have:

Add one more cloud resource: Alibaba Cloud RocketMQ

---

addons/terraform-alibaba/definitions/terraform-alibaba-amqp.yaml

Added ComponentDefinition for Alibaba Cloud AMQP
I have:

Add one more cloud resource: Alibaba Cloud AMQP

---

addons/terraform-aws/definitions/terraform-aws-subnet.yaml
addons/terraform-aws/definitions/terraform-aws-vpc.yaml

Added ComponentDefinition for AWS VPC and Subnet
I have:

Add cloud resources: AWS VPC and Subnet

---

addons/terraform-azure/definitions/terraform-azure-resource-group.yaml
addons/terraform-azure/definitions/terraform-azure-subnet.yaml
addons/terraform-azure/definitions/terraform-azure-virtual-network.yaml

Added one more cloud resource ComponentDefinition
I have:

Add cloud resource Azure Resource Group

---

addons/terraform-aws/definitions/terraform-aws-security-group.yaml

Added cloud resource ComponentDefinition AWS Security Group
I have:

Add cloud resource: AWS Security Group

---

addons/velaux/metadata.yaml
addons/velaux/resources/parameter.cue

Feat: upgrade velaux to 1.2.3

---

addons/terraform-gcp/metadata.yaml
addons/terraform-gcp/readme.md
addons/terraform-gcp/resources/account-creds.cue
addons/terraform-gcp/resources/parameter.cue
addons/terraform-gcp/resources/provider.cue
addons/terraform-gcp/template.yaml
hack/addons/terraform/provider-GCP.yaml

Signed-off-by: Avery Qi <2225992901@qq.com>
add provider-GCP.yaml and generate gcp addon.
I have:

add gcp provider and generate addon

---

addons/terraform-baidu/metadata.yaml
addons/terraform-baidu/readme.md
addons/terraform-baidu/resources/account-creds.cue
addons/terraform-baidu/resources/parameter.cue
addons/terraform-baidu/resources/provider.cue
addons/terraform-baidu/template.yaml

Signed-off-by: double12gzh <double12gzh@163.com>
Add baidu addons
I have:

Add baidu addons

---

addons/terraform-gcp/definitions/terraform-gcp-network.yaml

Signed-off-by: Nicola115 <2225992901@qq.com>
add resource gcp_network into definitions. 
I have:

generate resource: gcp_network

---

addons/terraform-baidu/definitions/terraform-baidu-vpc.yaml

Added a cloud resource Terraform Baidu Cloud addon
I have:

Add VPC for terraform-baidu

---

addons/terraform-alibaba/definitions/terrafrom-alibaba-nas.yaml
addons/terraform-alibaba/definitions/terrafrom-alibaba-security-group.yaml
addons/terraform-alibaba/definitions/terrafrom-alibaba-slb.yaml

add nas, slb, sg resources

---

addons/terraform/resources/terraform-controller.cue

* Support Baidu Cloud by @zzxwill in https://github.com/oam-dev/terraform-controller/pull/240
* Code refactor by @zzxwill in https://github.com/oam-dev/terraform-controller/pull/241
* Add UT by @zzxwill in https://github.com/oam-dev/terraform-controller/pull/242
* Add examples for Baidu provider by @zzxwill in https://github.com/oam-dev/terraform-controller/pull/243
I have:

Upgrade Terraform Controller

---

addons/terraform-alibaba/definitions/terraform-alibaba-rds-preview.yaml

ComponentDefinition alibaba-rds-preview is a preview of rds, which
supports database initialization
I have:

Add Alibaba RDS preview ComponentDefinition

---

addons/velaux/resources/views.cue

add `ignoreCollectPodKindMap` to filter the k8s resource avoid invalid query, improve query efficiency
I have:

Fix: update the component-pod-view of velaux addon

---

addons/terraform-alibaba/definitions/terraform-alibaba-eip-slb-ecs-rds.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-kms.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-kubernetes-networking
addons/terraform-alibaba/definitions/terraform-alibaba-market-tensorflow.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-mns-queue.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-mns-topic.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-mongodb-multi.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-network-with-nat.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-private-zone.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-rabbitmq.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-ram-fc.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-ram.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-remote-backend.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-slb-acl.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-slb-listener.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-slb-rule.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-vpc-ecs-eip.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-vpc-privatelink-connection.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-vpn-gateway.yaml
addons/terraform-alibaba/metadata.yaml

Added some cloud resoures from Alibaba Cloud which has been verified by Alibaba Terraform
team, and which are in regression tests.
I have:

Add Alibaba Cloud resources

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

- Change json tag of spec.Region to customRegion in Configuration
I have:

Upgrade version of Terraform addon

---

addons/terraform-aws/definitions/terraform-aws-mq.yaml
addons/terraform-gcp/definitions/terraform-gcp-mq.yaml

Added cloud resources MQ for AWS and GCP
I have:

Add MQ for AWS and GCP

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

- bugfix get TF Outputs type err
- Fix security issue by upgrading "github.com/go-yaml/yaml"
- add .status.observedGeneration to Configuration
- Ensusre credentials are retrieved before assemble a job or delete Configuration
- Upgrade go version to 1.17 in Dockerfile
- Switch Configuration API from v1beta1 to v1beta2
Signed-off-by: Anoop Gopalakrishnan <anoop2811@aol.in>
I have:

Upgrade terraform controller version to 0.4.2

---

experimental/addons/velaux-dev/metadata.yaml
experimental/addons/velaux-dev/readme.md
experimental/addons/velaux-dev/readme_cn.md
experimental/addons/velaux-dev/resources/apiserver.cue
experimental/addons/velaux-dev/resources/parameter.cue
experimental/addons/velaux-dev/resources/velaux.cue
experimental/addons/velaux-dev/resources/views.cue
experimental/addons/velaux-dev/schemas/addon-uischema-velaux.yaml
experimental/addons/velaux-dev/schemas/component-uischema-k8s-objects.yaml
experimental/addons/velaux-dev/schemas/component-uischema-task.yaml
experimental/addons/velaux-dev/schemas/component-uischema-webservice.yaml
experimental/addons/velaux-dev/schemas/trait-uischema-scaler.yaml
experimental/addons/velaux-dev/schemas/trait-uischema-storage.yaml
experimental/addons/velaux-dev/schemas/workflowstep-uischema-deploy2env.yaml
experimental/addons/velaux-dev/schemas/workflowstep-uischema-notification.yaml
experimental/addons/velaux-dev/schemas/workflowstep-uischema-webhook.yaml
experimental/addons/velaux-dev/template.yaml

Feat: add addon velaux-dev

---

addons/terraform-alibaba/definitions/terraform-alibaba-dns.yaml

Add one more cloud resource: Alibaba DNS.
We've use it to create new DNS records on our domain in our ACK cluster, it works. I replace the terraform configuration with alibaba official terraform module: https://github.com/terraform-alicloud-modules/terraform-alicloud-dns.git
see [example.zip](https://github.com/oam-dev/catalog/files/8231441/example.zip)
I have:

[Addon]Add one more cloud resource: Alibaba DNS

---

experimental/addons/argocd/definitions/application.cue
experimental/addons/argocd/definitions/clusterCred.cue
experimental/addons/argocd/definitions/project.cue
experimental/addons/argocd/definitions/repoCred.cue
experimental/addons/argocd/metadata.yaml
experimental/addons/argocd/readme.md
experimental/addons/argocd/template.yaml
test/e2e-test/hack/addon-vela-test.sh

Signed-off-by: cezhang <c1zhang.dev@gmail.com>
I have:

Feat: ArgoCD addon

---

addons/terraform-ucloud/metadata.yaml
addons/terraform-ucloud/readme.md
addons/terraform-ucloud/resources/parameter.cue
addons/terraform-ucloud/resources/ucloud-account-creds.cue
addons/terraform-ucloud/resources/ucloud-provider.cue
addons/terraform-ucloud/template.yaml

[Addon]Add ucloud addons

---

addons/fluxcd/schemas/component-uischema-helm.yaml

This PR depends on oam-dev/kubevela#3461  oam-dev/velaux#398
I have:

Feat: change the helm component ui schema definition

---

addons/fluxcd/schemas/component-uischema-helm.yaml

Revert "Feat: change the helm component ui schema definition"

---

addons/terraform-alibaba/definitions/terraform-alibaba-ack.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-ask.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-eip.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-oss.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-rds-preview.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-rds.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-redis.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-sls-project.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-sls-store.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-vpc.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-vswitch.yaml

Add an annotation to mark a cloud resources is verified.
I have:

Mark verified cloud resources

---

addons/README.md
experimental/addons/README.md

Signed-off-by: GitHub <noreply@github.com>
I have:

Fix: Addon List

---

.github/workflows/addon.yaml

Fix: fix endpoint

---

addons/dex/schemas/component-uischema-config-dex-connector.yaml

Feat: add uischema for the dex config definition

---

addons/velaux/metadata.yaml

Fix: change velaux addon version

---

addons/rollout/metadata.yaml
addons/rollout/resources/parameter.cue
addons/rollout/resources/rollout-controller.cue

Feat: change the rollout version to 1.3.0

---

addons/fluxcd/definitions/config-helm-repository.yaml

should block until https://github.com/oam-dev/kubevela/pull/3595 merged.
I have:

Feat: helm repo support basic-auth

---

addons/dex/definitions/dex-connectors-def.yaml
addons/dex/metadata.yaml

fix dex addon configs
I have:
/cc @barnettZQG

Fix: fix dex addon configs

---

addons/dex/schemas/component-uischema-config-dex-connector.yaml

Fix: change the ui schema of the dex config definition

---

addons/velaux/metadata.yaml
addons/velaux/readme.md
addons/velaux/readme_cn.md

Merge this after 1.3.1 is released.

Feat: upgrade the VelaUX addon to 1.3.1

---

addons/fluxcd/definitions/config-helm-repository.yaml

Fix: helm config empty username and pasword

---

.github/workflows/registry.yaml

Fix: fix failed CI image push

---

.github/workflows/addon-test.yaml
addons/fluxcd/definitions/helm-release-def.yaml
test/e2e-test/hack/addon-vela-test.sh

ignore the empty secret ref
due to the [flaky test](https://github.com/oam-dev/catalog/runs/6036708880?check_suite_focus=true) of modeling-server, which caused by this pr. pending the test firstly. Will be fixed by @FogDong 
I have:

Fix: ignore the empty secret ref

---

addons/velaux/metadata.yaml

Chore: change the VelaUX version to 1.3.2

---

addons/dex/definitions/dex-connectors-def.yaml
addons/dex/schemas/component-uischema-config-dex-connector.yaml

fix dex ldap configs
I have:
/cc @barnettZQG

Fix: fix dex ldap configs

---

Makefile
check-semver.sh
go.mod
go.sum
hack/addons/syn_addon_package.go
test/e2e-test/hack/check-semver.sh

1.  Due to #325   `kubevela.io` addon set a un semantic version, the helm index func generate wrong index.yaml file,  like this:
fix the error index.yaml
2. add check semver script.
I have:

Fix: fix index file and check semver script

---

addons/fluxcd/metadata.yaml
experimental/addons/README.md
experimental/addons/argocd/metadata.yaml

Chore: modify experimental readme

---

addons/velaux/metadata.yaml

Chore: upgrade the VelaUX addon to 1.3.4

---

addons/fluxcd/readme.md

Add more information for README.md

---

experimental/addons/dapr/definitions/dapr-publish-injection-trait-def.yaml
experimental/addons/dapr/definitions/dapr-publish-message-broker-trait-def.yaml
experimental/addons/dapr/definitions/dapr-subscribe-injection-trait-def.yaml
experimental/addons/dapr/definitions/dapr-subscription-trait-def.yaml
experimental/addons/dapr/metadata.yaml
experimental/addons/dapr/readme.md
experimental/addons/dapr/template.yaml
test/e2e-test/hack/addon-vela-test.sh

add dapr addon fixed https://github.com/oam-dev/kubevela/issues/609
since I don't use dapr much, there are not too many user story now, please create issue in the community, I will updated this addon continually

feat: add dapr addon

---

addons/fluxcd/definitions/helm-release-def.yaml
addons/fluxcd/definitions/json-patch.yaml
addons/fluxcd/definitions/kustomize.yaml
addons/fluxcd/definitions/strategy-merge.yaml
addons/fluxcd/metadata.yaml
addons/fluxcd/resources/crds/bucket.yaml
addons/fluxcd/resources/crds/git-repo.yaml
addons/fluxcd/resources/crds/helm-chart.yaml
addons/fluxcd/resources/crds/helm-repo.yaml
addons/fluxcd/resources/crds/kustomize.yaml
addons/fluxcd/resources/deployment/helm-controller.yaml
addons/fluxcd/resources/deployment/image-automation-controller.yaml
addons/fluxcd/resources/deployment/image-reflector-controller.yaml
addons/fluxcd/resources/deployment/kustomize-controller.yaml
addons/fluxcd/resources/deployment/source-controller.yaml
addons/fluxcd/resources/rbac/crd-controller.yaml

Signed-off-by: s4rd1nh4 <diego.milhomes@gmail.com>
Upgrade Flux addon to address the recent vulnerabilities.
https://fluxcd.io/blog/2022/05/may-2022-security-announcement/
v1beta2 API is backward compatible with v1beta1 - https://github.com/fluxcd/flux2/discussions/2567
I have:

[Addon] Upgrade Flux Addon

---

addons/ocm-gateway-manager-addon/metadata.yaml
addons/ocm-gateway-manager-addon/template.yaml
experimental/addons/example/resources/configmap.cue
experimental/addons/example/template.yaml
experimental/addons/istio/metadata.yaml
experimental/addons/istio/template.yaml
hack/addons/terraform/terraform-provider-scaffold/resources/account-creds.cue
hack/addons/terraform/terraform-provider-scaffold/resources/provider.cue

Signed-off-by: s4rd1nh4 <diego.milhomes@gmail.com>
Migrate raw to k8s-objects
Fixes #292
I have:

[Addon] Fix - deprecated raw component

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

Upgraded Terraform Controller to version of v0.7.0:
- use alpine-based image
- add huaweicloud support
- Support force deletion of Configuration
I have:

Feat: upgrade Terraform addon

---

experimental/addons/mysql-operator/README.md
experimental/addons/mysql-operator/definitions/mysql-cluster.cue
experimental/addons/mysql-operator/metadata.yaml
experimental/addons/mysql-operator/resources/mysql-operator.cue
experimental/addons/mysql-operator/resources/parameter.cue
experimental/addons/mysql-operator/template.yaml
test/e2e-test/hack/addon-vela-test.sh

mysql-operator

---

.github/workflows/addon-test.yaml
addons/velaux/metadata.yaml
addons/velaux/resources/parameter.cue
addons/velaux/resources/resource-detail-view.yaml
addons/velaux/resources/velaux.cue
addons/velaux/resources/views.cue
addons/velaux/schemas/addon-uischema-velaux.yaml
addons/velaux/schemas/workflowstep-uischema-deploy.yaml

refer to https://github.com/kubevela/kubevela/pull/3901
This PR should be pending before 1.4.0 is released

Feat: upgrade the VelaUX addon to 1.4.0-beta.2

---

addons/traefik/definitions/https-route.cue
addons/velaux/metadata.yaml

Chore: change the VelaUX version to 1.4.0

---

addons/fluxcd/readme.md
addons/vegeta/definitions/vegeta.cue
addons/vegeta/metadata.yaml
addons/vegeta/readme.md

Trait:vegeta

---

addons/fluxcd/metadata.yaml
addons/fluxcd/resources/deployment/helm-controller.yaml
addons/fluxcd/resources/deployment/image-automation-controller.yaml
addons/fluxcd/resources/deployment/image-reflector-controller.yaml
addons/fluxcd/resources/deployment/kustomize-controller.yaml
addons/fluxcd/resources/deployment/source-controller.yaml

[Addon] Feat - bump deps flux

---

addons/fluxcd/definitions/helm-release-def.yaml
addons/fluxcd/metadata.yaml
addons/fluxcd/resources/crds/bucket.yaml
addons/fluxcd/resources/crds/git-repo.yaml
addons/fluxcd/resources/crds/helm-chart.yaml
addons/fluxcd/resources/crds/helm-repo.yaml
examples/fluxcd/oci-registry-helm.yaml

Support the helm oci registry.
Fix: https://github.com/kubevela/kubevela/issues/3229
Fix: https://github.com/kubevela/kubevela/issues/3421
I have:

Feat: support helm OCI type registry

---

addons/fluxcd/definitions/kustomize.yaml

Fixes # adjust fluxcd kustomize, support for more native fields
I have:

[Addon] Feat: adjust fluxcd kustomize, support for more native fields

---

addons/fluxcd/definitions/helm-release-def.yaml
addons/fluxcd/metadata.yaml
examples/fluxcd/helm-values-files.yaml

support values file select
Fixes https://github.com/kubevela/kubevela/issues/3909
Demo:
```yaml
cat <<EOF | vela up -f -
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
name: hello-kubernetes
spec:
components:
- name: hello-kubernetes
type: helm
properties:
repoType: "helm"
url: "https://wangyikewxgm.github.io/my-charts/"
chart: "hello-kubernetes-chart"
version: "0.1.0"
EOF
```
```shelll
vela port-forward hello-kubernetes
```
You will see
Then:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
name: hello-kubernetes
spec:
components:
- name: hello-kubernetes
type: helm
properties:
repoType: "helm"
url: "https://wangyikewxgm.github.io/my-charts/"
chart: "hello-kubernetes-chart"
version: "0.1.0"
valuesFiles:
- "values-production.yaml"
EOF
```
Will see: …

Feat: support values file select

---

addons/velaux/metadata.yaml

Feat: change the VelaUX version to 1.4.2

---

addons/vela-prism/README.md
addons/vela-prism/metadata.yaml
addons/vela-prism/resources/parameter.cue
addons/vela-prism/resources/vela-prism.cue
addons/vela-prism/template.yaml

addon:vela-prism

---

addons/cert-manager/metadata.yaml
addons/dex/metadata.yaml
addons/flink-kubernetes-operator/metadata.yaml
addons/fluxcd/metadata.yaml
addons/fluxcd/readme.md
addons/kruise-rollout/metadata.yaml

[Addon]fix error images link

---

hack/addons/syn_addon_package.go

Formatted hack/addons/syn_addon_package.go, so it won't disturbe any
other PRs.
Signed-off-by: Zheng Xi Zhou <zhengxi.zzx@alibaba-inc.com>
I have:

Fix: format hack/addons/syn_addon_package.go

---

experimental/addons/crossplane-aws/definitions/aws-s3.cue
experimental/addons/crossplane-aws/definitions/crossplane-aws.cue
experimental/addons/crossplane-aws/metadata.yaml
experimental/addons/crossplane-aws/readme.md
experimental/addons/crossplane-aws/resources/provider.yaml
experimental/addons/crossplane-aws/template.yaml
experimental/addons/crossplane/metadata.yaml
experimental/addons/crossplane/readme.md
experimental/addons/crossplane/resources/crossplane.cue
experimental/addons/crossplane/template.yaml

Added experimental add-ons for
- Crossplane
- AWS provider for Crossplane
Signed-off-by: Zheng Xi Zhou <zhengxi.zzx@alibaba-inc.com>
I have:

Feat: add add-ons Crossplane and AWS provider

---

README.md
addons/rollout/metadata.yaml
addons/vela-prism/metadata.yaml

[Doc] Refine addon readme.

---

.github/PULL_REQUEST_TEMPLATE.md

modify pull request tempalte

---

addons/traefik/definitions/https-route.cue
addons/velaux/metadata.yaml
addons/velaux/schemas/component-uischema-task.yaml
addons/velaux/schemas/component-uischema-webservice.yaml

[Addon] Feat: upgrade the VelaUX to 1.4.3

---

addons/fluxcd/definitions/helm-release-def.yaml

Signed-off-by: huiwq1990 <huiwq1990@163.com>
I have:

Fix: cue format

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

- Add support for custom s3 backend
- Enhance S3Backend
- Add some Terraform native examples
- Fix: Terraform state is being overwritten each time
Signed-off-by: Zheng Xi Zhou <zhengxi.zzx@alibaba-inc.com>
I have:

Upgrade Terraform addon

---

addons/terraform-alibaba/definitions/terraform-alibaba-ecs.yaml

Feat: add ecs component

---

addons/kruise-rollout/definitions/kruise-rollout.cue

Signed-off-by: Charlie Chiang <charlie_c_0129@outlook.com>
Fixed a typo in CUE path.
I have:

[Addon] Fix: correct ingress name in kruise rollout

---

addons/fluxcd/definitions/helm-release-def.yaml
addons/fluxcd/metadata.yaml

add retry time paramter

---

addons/cloudshell/metadata.yaml
addons/cloudshell/readme.md
addons/cloudshell/template.yaml
addons/velaux/metadata.yaml

[Addon] Add the CloudShell addon

---

addons/fluxcd/definitions/config-helm-repository.yaml
addons/fluxcd/schemas/config-helm-repository.yaml

Fluxcd support self signed repo

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml

fix fluxcd health check

---

addons/traefik/definitions/config-tls-certificate.cue
addons/traefik/metadata.yaml
addons/traefik/readme.md
addons/traefik/schemas/component-uischema-config-tls-certificate.yaml
addons/velaux/metadata.yaml
addons/velaux/views/resource-view.cue

[Addon] change the uischema of the traefik

---

addons/kruise-rollout/metadata.yaml
addons/kruise-rollout/template.yaml

[Addon] upgrade kruise-rollout to fix label bug

---

addons/mysql-exporter/README.md
addons/mysql-exporter/definitions/mysql-exporter-component.cue
addons/mysql-exporter/definitions/mysql-exporter-trait.cue
addons/mysql-exporter/metadata.yaml
addons/mysql-exporter/schemas/component-uischema-mysql-exporter-server.yaml
addons/mysql-exporter/schemas/trait-uischema-mysql-exporter.yaml
addons/mysql-exporter/template.yaml

[Addon] add the mysql-exporter addon

---

addons/netlify/README.md
addons/netlify/definitions/netlify.cue
addons/netlify/metadata.yaml

addon:netlify-workload

---

.github/CODEOWNERS

Update CODEOWNERS for addons

---

.github/workflows/addon-test.yaml
addons/velaux/metadata.yaml
addons/velaux/schemas/policy-uischema-override.yaml
addons/velaux/views/component-pod-view.cue

[Addon] upgrade the VelaUX to 1.5.0-beta.1

---

.github/workflows/addon-test.yaml
addons/cloudshell/metadata.yaml
addons/cloudshell/readme.md
addons/cloudshell/template.yaml
addons/velaux/metadata.yaml
test/e2e-test/addon-test/main.go

Feat: upgrade VelaUX to 1.5.0-beta.2

---

.github/workflows/addon-test.yaml

Feat: upgrade ci cli version

---

addons/ingress-nginx/metadata.yaml
addons/ingress-nginx/parameter.cue
addons/ingress-nginx/resources/ingress-nginx.cue
addons/ingress-nginx/template.cue
addons/ingress-nginx/template.yaml

1. upgrade ingress-nginx addon to fix image pull error
2. refactor ingress controller use cue template to render app
Should wait until 
I have:

[Addon] upgrade ingress-nginx addon to fix image pull error

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
addons/terraform-alibaba/definitions/terraform-alibaba-rds-database.yaml
addons/terraform-alibaba/definitions/terraform-alibaba-rds-instance.yaml
addons/terraform-alibaba/metadata.yaml

Signed-off-by: qiaozp <qiaozhongpei.qzp@alibaba-inc.com>
Added two definition for terraform-alibaba (rds-instance, rds-database) and update PR template.
Test by hand.
I have:

[Addon] add rds-instance and rds-database definition

---

addons/vela-prism/README.md

[Addon] Update vela-prism readme

---

addons/grafana-definitions/definitions/grafana-access.cue
addons/grafana-definitions/definitions/grafana-dashboard.cue
addons/grafana-definitions/definitions/grafana-datasource.cue
addons/grafana-definitions/definitions/install-kubernetes-api-datasource.cue
addons/grafana-definitions/definitions/install-prometheus-datasource-from-addon.cue
addons/grafana-definitions/metadata.yaml
addons/grafana-definitions/readme.md
addons/grafana-definitions/template.yaml
addons/grafana/metadata.yaml
addons/grafana/parameter.cue
addons/grafana/readme.md
addons/grafana/resources/grafana-access.cue
addons/grafana/resources/grafana-dashboard-applications-overview.cue
addons/grafana/resources/grafana-dashboard-deployment-overview.cue
addons/grafana/resources/grafana-dashboard-kubernetes-apiserver.cue
addons/grafana/resources/grafana-dashboard-kubevela-system.cue
addons/grafana/resources/grafana-storage.cue
addons/grafana/resources/grafana.cue
addons/grafana/template.cue
test/e2e-test/addon-test/main.go

1. grafana-definitions addon provide necessary definitions for installing grafana addon or using vela-prism grafana api.
2. grafana addon will automatically lookup prometheus endpoints from addon-prometheus application and install it into grafana.
I have:

[Addon] grafana addon

---

.github/CODEOWNERS
README.md

[Chore] Add some info for repo

---

addons/grafana/parameter.cue
addons/grafana/resources/grafana-dashboard-kubevela-system.cue
addons/grafana/resources/grafana-storage.cue
addons/grafana/template.cue
addons/kube-state-metrics/parameter.cue
addons/kube-state-metrics/template.cue
addons/node-exporter/parameter.cue
addons/node-exporter/template.cue
addons/prometheus-server/parameter.cue
addons/prometheus-server/resources/prometheus-server.cue
addons/prometheus-server/resources/prometheus-storage.cue
addons/prometheus-server/template.cue
addons/vela-prism/parameter.cue
addons/vela-prism/template.cue
test/e2e-test/addon-test/main.go

1. Modify `xxx: *"" | string` to `xxx?: string` to fit velaux openapi usage.
2. Move parameter.name to const.name to fix velaux openapi usage.
3. Fix Grafana KubeVela-System Dashboard not work when thanos is not installed.
I have:

[Addon] metrics addons

---

.github/workflows/addon-test.yaml
addons/fluxcd/definitions/json-patch.cue
addons/fluxcd/metadata.yaml
addons/terraform/metadata.yaml

[Addon]: rename json patch def avoid to conflict with official trait

---

.github/workflows/addon-test.yaml
addons/cloudshell/metadata.yaml
addons/cloudshell/readme.md
addons/cloudshell/template.yaml
addons/dex/metadata.yaml
addons/dex/readme.md
addons/velaux/metadata.yaml
addons/velaux/views/component-pod-view.cue
addons/velaux/views/component-service-view.cue

[Addon] upgrade to 1.5.0

---

addons/cloudshell/metadata.yaml
addons/cloudshell/readme.md
addons/cloudshell/template.yaml

Key changes: 
* Reduced cloudshell Pod startup time.
I have:

[Addon] Upgrade the cloudshell operator to 0.3.0

---

addons/velaux/metadata.yaml
addons/velaux/resources/velaux.cue

[Addon] upgrade VelaUX to 1.5.2

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

Upgrade terraform to 1.0.11
I have:

[Addon] Upgrade terraform to 1.0.11

---

hack/addons/terraform/terraform-provider-scaffold/resources/account-creds.cue
hack/addons/terraform/terraform-provider-scaffold/resources/provider.cue

Fix the wrong scaffold. 
See problem here: https://github.com/kubevela/catalog/pull/443#discussion_r947344448
I have:

[Addon] Fix provider generate scalffold

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

Bump terraform version to v0.7.7
I have:

[Addon] Bump terraform to 1.0.13

---

examples/kruise/cloneset.yaml
experimental/addons/kruise/definitions/cloneset.yaml
experimental/addons/kruise/template.yaml

kruise addon will be an example to teach user how to config toppoloy rules. So refine it.
I have:

[Addon] fix error kruise addon

---

addons/velaux/parameter.cue
addons/velaux/resources/apiserver.cue
addons/velaux/resources/velaux.cue

Support HA deployment for the VelaUX.
This change does not need to upgrade the version.
I have:

[Addon] Add replica parameter for the velaux

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Docs: small change  about addon promote rules

---

addons/kruise-rollout/definitions/kruise-rollout.cue
addons/kruise-rollout/metadata.yaml
examples/kruise/rollout-batch-partition.yaml
examples/kruise/rollout-gateway.yaml
vela.yaml

Addon: update kruise rollout addon traitDefinition

---

addons/velaux/metadata.yaml

Signed-off-by: qiaozp <qiaozhongpei.qzp@alibaba-inc.com>
I have:
I have:

[Addon] upgrade velaux to 1.5.4

---

test/e2e-test/terraform-test/terraform_test.go
test/e2e-test/terraform-test/testdata/rds-database.yaml
test/e2e-test/terraform-test/testdata/rds-instance.yaml
test/e2e-test/terraform-test/testdata/redis.yaml

minor fix on terraform e2e

---

test/e2e-test/terraform-test/terraform_test.go
test/e2e-test/terraform-test/testdata/ecs.yaml

Add ECS to regular check, this will cover the [blog](https://kubevela.io/blog/2022/06/27/terraform-integrate-with-vela#part-2-fixing-the-developer-experience-of-kubernetes-port-forwarding) example on kubevela.io
I have:

[Addon] Add ECS to regular check

---

examples/kube-trigger/sample.yaml
experimental/addons/kube-trigger/README.md
experimental/addons/kube-trigger/definitions/apprev-bumper.cue
experimental/addons/kube-trigger/definitions/trigger-service.cue
experimental/addons/kube-trigger/metadata.yaml
experimental/addons/kube-trigger/parameter.cue
experimental/addons/kube-trigger/resources/deployment.cue
experimental/addons/kube-trigger/resources/rbac.cue
experimental/addons/kube-trigger/resources/role.cue
experimental/addons/kube-trigger/resources/standard.oam.dev_triggerinstances.yaml
experimental/addons/kube-trigger/resources/standard.oam.dev_triggerservices.yaml
experimental/addons/kube-trigger/resources/topology.cue
experimental/addons/kube-trigger/template.cue

Add kube-trigger addon.
I have:

[Addon] add kube-trigger addon

---

addons/velaux/metadata.yaml
addons/velaux/resources/velaux.cue

[Addon] Upgrade the VelaUX to 1.5.5

---

experimental/addons/clickhouse/metadata.yaml
experimental/addons/dapr/metadata.yaml

[Addon] fix broken image error

---

.github/PULL_REQUEST_TEMPLATE.md

Optimize addon contribution checklist.
I have:
I have:

[Doc] Optimize pr check list

---

addons/velaux/metadata.yaml

[Addon] upgrade the VelaUX to 1.5.6

---

experimental/addons/clickhouse/definitions/clickhouse.cue
experimental/addons/clickhouse/metadata.yaml
experimental/addons/clickhouse/parameter.cue
experimental/addons/clickhouse/resources/ck-op-dashboard.cue
experimental/addons/clickhouse/resources/ck-op.cue
experimental/addons/clickhouse/template.cue

Fix: click house addon

---

addons/cloudshell/metadata.yaml
addons/cloudshell/readme.md
addons/cloudshell/template.yaml

Upgrade the vela CLI version to v1.5.6
I have:

[Addon] upgrade the CloudShell to 0.0.4

---

addons/prometheus-server/definitions/prometheus-scrape.cue
addons/prometheus-server/metadata.yaml
experimental/addons/clickhouse/parameter.cue
experimental/addons/clickhouse/resources/ck-op.cue
experimental/addons/clickhouse/resources/grafana-dashboadr.cue
experimental/addons/clickhouse/template.cue

Feat: enhance prometheus scrape definition 

---

addons/velaux/parameter.cue
addons/velaux/resources/velaux.cue

[Addon] add velaux argument: nodeport

---

addons/fluxcd/parameter.cue
addons/fluxcd/template.cue

Fix: fix fluxcd cue files
/cc @wangyikewxgm @wonderflow 

Fix: fix fluxcd cue files

---

README.md
addons/vela-prism/README.md

Signed-off-by: Diego Pinheiro <diego.milhomes@gmail.com>
I have:

fix - broken link

---

addons/fluxcd/schemas/component-uischema-helm.yaml

[Addon] optimize fluxcd addon helm compDef parameter UISchema

---

experimental/addons/clickhouse/definitions/clickhouse.cue

add health check for clickhouse

---

.gitignore
addons/trivy-operator/definitions/trivy.cue
addons/trivy-operator/parameter.cue
addons/trivy-operator/resources/trivy-service.cue

Add trivy check definition.
Example:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
name: example
namespace: default
spec:
components:
- name: server-test
type: webservice
properties:
port: 8000
image: nginxinc/nginx-unprivileged:latest
workflow:
steps:
- name: apply-comp
type: apply-component
properties:
component: server-test
- name: image-scan
type: trivy-check
timeout: 15m
outputs:
- name: image-scan-result
valueFrom: message.data
properties:
url: <trivy-url>
image: nginxinc/nginx-unprivileged:latest
level:
- "CRITICAL"
- "HIGH"
- name: notification
type: notification
inputs:
- from: image-scan-result
parameterKey: slack.message.text
if: always
properties:
slack:
url:
value: <slack channel>
```
I have:
If this …

Feat: add trivy check definition

---

addons/trivy-operator/definitions/trivy.cue
examples/trivy-operator/trivy-check-example.yaml

Fix: fix trivy def and add example

---

addons/fluxcd/definitions/helm-release-def.cue

[Addon] add default value for git branch in helm

---

.github/issue-commands.json
.github/workflows/issue-commands.yml

add issue command

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml

- Add `sourceName` optional field
- Move `HelmRelease` workload to `output` field and move optional field `repo` into `outputs` field
- Update `helm.attributes.status` field
Ref #https://github.com/kubevela/kubevela/issues/4820
I use the HelmChart in https://github.com/chengleqi/hello-kubernetes-demo to test helm
I have:

[Addon] Add optional field sourceName for helm

---

addons/grafana-definitions/definitions/import-grafana-dashboard.cue
addons/grafana-definitions/metadata.yaml
addons/grafana/metadata.yaml
addons/grafana/resources/grafana-dashboard-applications-overview.cue
addons/grafana/resources/grafana-dashboard-daemonset-overview.cue
addons/grafana/resources/grafana-dashboard-deployment-overview.cue
addons/grafana/resources/grafana-dashboard-kubernetes-apiserver.cue
addons/grafana/resources/grafana-dashboard-kubevela-system.cue
addons/grafana/resources/grafana-dashboard-statefulset-overview.cue
addons/grafana/template.cue
addons/loki/definitions/collect-logs.cue
addons/loki/metadata.yaml
addons/loki/parameter.cue
addons/loki/resources/agent-promtail.cue
addons/loki/resources/agent-vector.cue
addons/loki/resources/agent.cue
addons/loki/resources/loki-config.cue
addons/loki/resources/loki.cue
addons/loki/template.cue
addons/prometheus-server/metadata.yaml
addons/prometheus-server/resources/prometheus-config.cue

[Addon] update metrics addons

---

addons/fluxcd/metadata.yaml
addons/fluxcd/parameter.cue
addons/fluxcd/template.cue
addons/model-training/definitions/training-comp-def.yaml
addons/model-training/metadata.yaml

Fix: fix model training addon definition

---

examples/clickhouse/ckapp.yaml
experimental/addons/clickhouse/definitions/clickhouse.cue
experimental/addons/clickhouse/readme.md
experimental/addons/clickhouse/template.cue

refine clickhouse addon

---

addons/grafana-definitions/definitions/import-grafana-dashboard.cue
addons/grafana-definitions/metadata.yaml
addons/grafana/metadata.yaml
addons/grafana/resources/grafana-dashboard-applications-overview.cue

[Addon] Feat: fix import grafana dashboard & enhance dashboard

---

experimental/addons/kruise/template.yaml

Fix: add resource relation cm in kruise

---

addons/vela-workflow/README.md
addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue
addons/vela-workflow/template.cue
test/e2e-test/addon-test/PENDING

Feat: add workflow addon

---

addons/vela-workflow/definitions/addon-operation.cue
addons/vela-workflow/definitions/clean-jobs.cue
addons/vela-workflow/metadata.yaml
addons/vela-workflow/template.cue
examples/vela-workflow/observerbility.yaml
examples/vela-workflow/test-error.yaml

vela workflow two steps for eanble addon by workflowRun
I have:

[Addon] vela workflow two steps for eanble addon by workflowRun

---

examples/vela-workflow/observerbility.yaml
examples/vela-workflow/test-error.yaml

[Example] Fix example of workflow

---

addons/vela-workflow/definitions/addon-operation.cue
addons/vela-workflow/definitions/clean-jobs.cue

1. add job backoff limit for failed.
2. clean pods.
I have:

[Addon] several optimize

---

addons/grafana/readme.md

Docs: add notice for  enabling grafana with low version kubevela

---

addons/velaux/metadata.yaml
addons/velaux/resources/velaux.cue
addons/velaux/views/cloud-resource-view.cue

[Addon] VelaUX upgrade to 1.5.8

---

experimental/addons/clickhouse/metadata.yaml

Signed-off-by: Charlie Chiang <charlie_c_0129@outlook.com>
Add version requirement for clickhouse addon. Since it uses `multiple comprehensions per list`, which is available in CUE v3.0, we need Vela v1.6.0-alpha.1 and later for CUE v0.4.3
https://github.com/kubevela/catalog/blob/178724832a5fc1c0e7cb0553c1f932cad239108f/experimental/addons/clickhouse/template.cue#L11-L16
Fixes part of #511
I have:

Fix: add version requirement for clickhouse

---

addons/loki/parameter.cue
addons/vela-workflow/definitions/addon-operation.cue

change vector controller image and fix failed candition
I have:

[Addon] change vector controller image and fix failed candition

---

addons/cloudshell/metadata.yaml
addons/cloudshell/readme.md
addons/cloudshell/template.yaml
addons/velaux/metadata.yaml
addons/velaux/resources/velaux.cue

[Addon] VelaUX and CloudShell upgrade to 1.6.0-beta.1

---

addons/grafana/metadata.yaml
addons/grafana/resources/grafana-dashboard-kubernetes-events.cue
addons/grafana/template.cue
addons/loki/metadata.yaml
addons/loki/resources/agent-vector-contoller.cue
addons/loki/resources/agent.cue
addons/loki/resources/event-logger.cue

1.  loki addon support Kubernetes events to log
2. events analytical dashboard.
I have:

[Addon] loki addon support Kubernetes events to log

---

addons/kube-state-metrics/metadata.yaml
addons/kube-state-metrics/resources/common.cue
addons/kube-state-metrics/resources/kube-state-metrics.cue
addons/kube-state-metrics/template.cue
addons/node-exporter/metadata.yaml
addons/node-exporter/resources/common.cue
addons/node-exporter/resources/node-exporter.cue
addons/node-exporter/template.cue
addons/prometheus-server/metadata.yaml
addons/prometheus-server/resources/common.cue
addons/prometheus-server/resources/post-deploy.cue
addons/prometheus-server/resources/prometheus-config.cue
addons/prometheus-server/resources/prometheus-server.cue
addons/prometheus-server/resources/prometheus-storage.cue
addons/prometheus-server/resources/thanos-query.cue
addons/prometheus-server/template.cue

Feat: upgrade metrics addons

---

addons/loki/definitions/file-logs-collector.cue
addons/loki/definitions/stdout-logs-collector.cue
addons/loki/metadata.yaml

optimize nginx application grafana dashboard
before:
after:
I have:

[Addon]loki addon for optimize-nginx-dashboard

---

addons/grafana/resources/grafana-dashboard-kubernetes-events.cue
addons/loki/definitions/stdout-logs-collector.cue

add cluster variable  for event log dashboard.
I have:

[Addon] small optimize for event log dashboard

---

addons/vela-workflow/definitions/addon-operation.cue

[Addon] create the addon operation job in the vela-system namespace

---

.github/CODEOWNERS
addons/loki/definitions/stdout-logs-collector.cue
addons/loki/metadata.yaml
examples/loki/collect-std-with-nginx-parser.yaml
examples/loki/collect-stdout-with-customzie-parser.yaml

1. add costomize parser vrl for loki addon 
2.  change dir owner
I have:

[Addon] add costomize parser vrl for loki addon and change dir owner

---

addons/loki/definitions/file-logs.cue
addons/loki/definitions/stdout-logs.cue
addons/loki/metadata.yaml
addons/loki/parameter.cue
addons/loki/resources/agent-vector.cue
addons/loki/resources/agent.cue
examples/loki/collect-file-log.yaml
examples/loki/collect-std-with-nginx-parser.yaml
examples/loki/collect-stdout-with-customzie-parser.yaml

refactor loki addon enable parameter 
before: 
vela addon enable loki agent=vector
after:
vela addon enable loki agent=vector stdout=all
-----
before: 
vela addon enable loki agent=vector-controller
after:
vela addon enable loki agent=vector 
I have:

[Addon] refactor loki parameter

---

addons/prometheus-server/definitions/prometheus-scrape.cue
addons/prometheus-server/metadata.yaml

Fix: prometheus scrape

---

addons/vela-workflow/definitions/apply-app.cue
addons/vela-workflow/definitions/apply-deployment.cue
addons/vela-workflow/definitions/read-app.cue
addons/vela-workflow/definitions/request.cue
addons/vela-workflow/metadata.yaml
addons/vela-workflow/template.cue

Feat: add defs in workflow addon
I have:

Feat: add defs in workflow addon

---

addons/velaux/metadata.yaml
addons/velaux/resources/velaux.cue
examples/vela-workflow/pipeline-observability-steps.yaml

[Addon] upgrade VelaUX to 1.6.0-beta.2

---

addons/cloudshell/metadata.yaml
addons/cloudshell/readme.md
addons/cloudshell/template.yaml
addons/velaux/metadata.yaml
addons/velaux/resources/velaux.cue

[Addon] upgrade VelaUX and CloudShell to v1.6.0

---

addons/o11y-definitions/definitions/grafana-dashboard-trait.cue
addons/o11y-definitions/definitions/install-datasource-from-config.cue
addons/o11y-definitions/metadata.yaml

Feat: add grafana dashboard trait

---

.github/CODEOWNERS
addons/vela-workflow/definitions/addon-operation.cue
addons/vela-workflow/metadata.yaml

[Addon] upgrade vela-workflow addon operation image

---

addons/vela-workflow/definitions/addon-operation.cue
addons/vela-workflow/definitions/apply-app.cue
addons/vela-workflow/definitions/clean-jobs.cue
addons/vela-workflow/definitions/read-app.cue
addons/vela-workflow/metadata.yaml

Feat: add scope label for workflowrun defs

---

addons/cloudshell/metadata.yaml
addons/cloudshell/readme.md
addons/cloudshell/template.yaml
addons/velaux/metadata.yaml

[Addon] upgrade VelaUX to 1.6.1

---

.github/workflows/addon-test.yaml
test/e2e-test/addon-test/PENDING
test/e2e-test/addon-test/main.go

[Addon] Fix ci workflow to remove all pendings

---

examples/vector-config/log2metric.yaml
experimental/addons/vector-config/definitions/log2metric.cue

- rename component `vector-config-log2metric` to `log2metric`
- add necessary attribute `workload: type: "autodetects.core.oam.dev"`
Codes has been tested with `vela addon enable <local path>`
I have:

[Addon] rename component in vector-config && add necessary attributes

---

addons/vela-workflow/definitions/addon-operation.cue
addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue
addons/vela-workflow/resources/crd.cue
addons/vela-workflow/resources/privileges.cue
addons/vela-workflow/resources/vela-workflow.cue
addons/vela-workflow/template.cue

Fix: refactor the workflow addon with raw resources

---

test/e2e-test/terraform-test/terraform_test.go
test/e2e-test/terraform-test/testdata/dedecated-kubernetes.yaml

[Addon] add ack e2e test

---

addons/fluxcd/definitions/kustomize.cue
addons/fluxcd/metadata.yaml

Add `imageRepository.interval` optional field
Ref: https://github.com/kubevela/kubevela/issues/4820#issuecomment-1285147393
I have:

[Addon] Add optional field imageRepository.interval for kustomize automation

---

addons/prometheus-server/definitions/prometheus-scrape.cue

Feat: set the attributes for the prometheus scrape trait

---

addons/fluxcd/metadata.yaml
addons/fluxcd/schemas/component-uischema-kustomize.yaml

Add uischema for kustomize
Ref: https://github.com/kubevela/kubevela/issues/4820
Result:
I think this order is more reasonable.
I have:

[Addon] Add uischema for kustomize

---

addons/kruise-rollout/definitions/kruise-rollout.cue
addons/velaux/metadata.yaml

[Addon] upgrade VelaUX to 1.6.3

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml

Fix: fix helm release health check

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml

Fix: fix health check for helmrepo

---

addons/cloudshell/readme.md
addons/cloudshell/template.yaml
addons/velaux/metadata.yaml

[Addon] upgrade the VelaUX to 1.6.4

---

addons/keda/README.md

Signed-off-by: HanMengnan <1448189829@qq.com>
Add a video example of Keda's autoscaling in CPU based trigger.
I have:

[example] Add a video example of Keda's autoscaling in CPU based trigger.

---

addons/terraform-alibaba/config-templates/alibaba-provider.cue
addons/vela-workflow/definitions/addon-operation.cue
addons/vela-workflow/definitions/apply-app.cue
addons/vela-workflow/definitions/apply-deployment.cue
addons/vela-workflow/definitions/apply-terraform-config.cue
addons/vela-workflow/definitions/apply-terraform-provider.cue
addons/vela-workflow/definitions/read-app.cue
addons/vela-workflow/definitions/request.cue
addons/vela-workflow/definitions/vela-cli.cue
addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue

Example here：https://github.com/kubevela/workflow/pull/95
I have:

Feat: add terraform step definitions in workflow

---

addons/loki/metadata.yaml
addons/loki/resources/common.cue
addons/loki/template.cue

Disable the recycle and state-keep of CRD resources in loki addon.
I have:

[Addon] disable statekeep and gc for crd resource in loki addon

---

addons/fluxcd/definitions/kustomize.cue
addons/fluxcd/metadata.yaml

Fixes kubevela/kubevela#4820
I have:

Fix: fix source name for image update

---

experimental/addons/process-exporter/README.md
experimental/addons/process-exporter/metadata.yaml
experimental/addons/process-exporter/parameter.cue
experimental/addons/process-exporter/resources/common.cue
experimental/addons/process-exporter/resources/process-exporter-config.cue
experimental/addons/process-exporter/resources/process-exporter.cue
experimental/addons/process-exporter/template.cue

Prometheus exporter for harvesting process metrics from /proc.
This addon is deployed as a Daemonset, which monitors all processes on the host by default.
Code has been tested on my local develop environment.
I have:

[Addon] add process-exporter addon

---

addons/trivy-operator/metadata.yaml

I have:
- [ x] New addon should be put in [experimental](https://github.com/kubevela/catalog/tree/master/experimental/addons).

Feat: add aqua trivy as trivy operator

---

test/e2e-test/terraform-test/terraform_test.go
test/e2e-test/terraform-test/testdata/dedicated-kubernetes.yaml

[Addon] Fix regular test waiting time and wrong app name

---

addons/velaux/metadata.yaml
addons/velaux/resources/velaux.cue

[Addon] upgrade VelaUX to 1.6.6

---

examples/backstage/app.yaml
experimental/addons/backstage/NOTES.cue
experimental/addons/backstage/README.md
experimental/addons/backstage/definitions/backstage.cue
experimental/addons/backstage/metadata.yaml
experimental/addons/backstage/parameter.cue
experimental/addons/backstage/resources/backstage.cue
experimental/addons/backstage/resources/vela-adapt.cue
experimental/addons/backstage/template.cue

Fixes https://github.com/kubevela/kubevela/issues/4842
I have:

Add a backstage addon

---

experimental/addons/backstage/NOTES.cue
experimental/addons/backstage/metadata.yaml
experimental/addons/backstage/parameter.cue
experimental/addons/backstage/resources/backstage.cue
experimental/addons/backstage/resources/vela-adapt.cue

backstage addon: add resource limit & update image, notes

---

experimental/addons/backstage/README.md

Add related repo to readme

---

README.md

refine addon readme for more detailed guides

---

experimental/addons/example-cue/metadata.yaml

Signed-off-by: bitliu <bitliu@tencent.com>

fix: typo of example-cue

---

addons/velaux/metadata.yaml
addons/velaux/views/event-view.cue

Fixes #576 
curl http://localhost:8000/api/v1/query?velaql=event-view{name=xxxx,namespace=xxxxx,cluster=xxxx,type=xxxx}
I have:

[addon velaux] add event-view

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml
test/e2e-test/addon-test/PENDING

Signed-off-by: hnd4r7 <307365651@qq.com>
I have:

Fix: helm release status not shown

---

README.md

Docs: small fix for readme

---

addons/velaux/metadata.yaml
addons/velaux/parameter.cue
addons/velaux/resources/apiserver.cue
addons/velaux/resources/privileges.cue
addons/velaux/template.cue

[Addon] upgrade VelaUX to 1.7.0-beta.2

---

addons/trivy-operator/definitions/aqua-trivy.cue
addons/trivy-operator/metadata.yaml
addons/vela-workflow/README.md
addons/vela-workflow/definitions/apply-app.cue
addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue

Fix: fix trivy scan definition and bump workflow addon

---

addons/velaux/metadata.yaml

[Addon] upgrade the VelaUX to 1.7.0

---

test/e2e-test/terraform-test/terraform_test.go

Remove aliyun dedicated kubernetes from regular check

---

experimental/addons/istio/template.yaml
test/e2e-test/addon-test/main.go

[CI] addon CI check for must change metadata when upgrade an addon

---

addons/vela-workflow/definitions/apply-app.cue
addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue
addons/vela-workflow/template.cue

Fix: add polices in workflow addon

---

experimental/addons/backstage/README.md
experimental/addons/backstage/metadata.yaml
experimental/addons/backstage/resources/vela-adapt.cue

support specify backstage system for app

---

addons/vela-workflow/metadata.yaml
addons/vela-workflow/template.cue

Fix: add policy for other native resources like role

---

addons/velaux/metadata.yaml

[VelaUX] upgrade to 1.7.2

---

addons/vela-workflow/metadata.yaml
addons/vela-workflow/template.cue

Fix: take over deployment of vela workflow

---

addons/grafana/metadata.yaml
addons/grafana/resources/common.cue
addons/grafana/resources/grafana-dashboard-kubernetes-pod.cue
addons/kube-state-metrics/metadata.yaml
addons/kube-state-metrics/resources/common.cue
addons/loki/metadata.yaml
addons/loki/resources/common.cue
addons/node-exporter/metadata.yaml
addons/node-exporter/resources/common.cue
addons/prometheus-server/metadata.yaml
addons/prometheus-server/resources/common.cue

Upgrade o11y addons to add `take-over` and `garbage-collect` policy for Namespace resources.
I have:

Fix: upgrade o11y addon with namespace policy

---

addons/flink-kubernetes-operator/metadata.yaml
addons/flink-kubernetes-operator/template.cue

Signed-off-by: yanghua <yanghua1127@gmail.com>
I have:

[Addon] Upgrade flink-kubernetes-operator version

---

addons/cert-manager/metadata.yaml
addons/cert-manager/template.cue
addons/trivy-operator/metadata.yaml
addons/trivy-operator/template.cue

[Addons] fix  error addons due to take over namespace policy

---

addons/terraform-alibaba/definitions/terraform-alibaba-security-group.yaml
addons/terraform-alibaba/metadata.yaml

terraform-alicloud-modules/terraform-alicloud-security-group have more powerful features to create security group. This PR switch the `alibaba-security-group` definition to refer to this module.
I have:

[Addon] switch back terraform-alicloud-modules/terraform-alicloud-security-group

---

test/e2e-test/terraform-test/terraform_test.go
test/e2e-test/terraform-test/testdata/security-group.yaml
test/e2e-test/terraform-test/testdata/vpc.yaml
test/e2e-test/terraform-test/testdata/vswitch.yaml

Feat: add vpc/vswitch/security-group to regular check

---

addons/terraform/metadata.yaml
addons/terraform/resources/terraform-controller.cue

Update terraform-controller to the latest version.

feat: updated terraform-controller to 0.7.9.

---

test/e2e-test/addon-test/main.go

code logic for addon  loop check
I have:

CI:  code logic for addon  loop check

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml
examples/fluxcd/helm-values-from.yaml

I add a parameter in HelmRelease named valuesFrom to support [valuesFrom](https://fluxcd.io/flux/components/helm/helmreleases/#:~:text=should%20be%20merged.-,ValuesFrom,-%5B%5DValuesReference%20%60json%3A%22valuesFrom) in fluxcd.
I test this code in my own cluster.
I have:

[Addon] feat: add valuesFrom in HelmRelease of fluxcd

---

experimental/addons/sae-apiserver-proxy/README.md
experimental/addons/sae-apiserver-proxy/metadata.yaml
experimental/addons/sae-apiserver-proxy/parameter.cue
experimental/addons/sae-apiserver-proxy/resources/apiservice.cue
experimental/addons/sae-apiserver-proxy/resources/proxy.cue
experimental/addons/sae-apiserver-proxy/resources/topo-tree.cue
experimental/addons/sae-apiserver-proxy/template.cue

Addon: sae-apiserver-proxy

---

addons/terraform-alibaba/config-templates/alibaba-provider.cue
addons/terraform-alibaba/metadata.yaml
addons/terraform-aws/config-templates/aws-provider.cue
addons/terraform-aws/metadata.yaml
addons/terraform-azure/config-templates/azure-provider.cue
addons/terraform-azure/metadata.yaml
addons/terraform-baidu/config-templates/baidu-provider.cue
addons/terraform-baidu/metadata.yaml
addons/terraform-ec/config-templates/ec-provider.cue
addons/terraform-ec/metadata.yaml
addons/terraform-gcp/config-templates/gcp-provider.cue
addons/terraform-gcp/metadata.yaml
addons/terraform-tencent/config-templates/tencent-provider.cue
addons/terraform-tencent/metadata.yaml
addons/terraform-ucloud/config-templates/ucloud-provider.cue
addons/terraform-ucloud/metadata.yaml

For[ #5468](https://github.com/kubevela/kubevela/pull/5468)
I have:

Fix: removes parameter name for terraform cloud-provider

---

addons/terraform/metadata.yaml
addons/terraform/resources/terraform-controller.cue

bump terraform chart to 0.7.10
I have:

[Addon] bump terraform chart to 0.7.10

---

addons/velaux/metadata.yaml

[Addon] upgrade the VelaUX to 1.7.4

---

addons/fluxcd/metadata.yaml
addons/fluxcd/schemas/component-uischema-helm.yaml

[Addon] fluxcd update uischema to support oci helm repo

---

.github/workflows/addon-test.yaml
addons/grafana/metadata.yaml
addons/grafana/resources/grafana-dashboard-applications-overview.cue
addons/grafana/resources/grafana-dashboard-kubevela-system.cue
addons/o11y-definitions/definitions/grafana-access.cue
addons/o11y-definitions/metadata.yaml
addons/prometheus-server/metadata.yaml
addons/prometheus-server/resources/prometheus-config.cue
addons/vela-core-shard-manager/README.md
addons/vela-core-shard-manager/metadata.yaml
addons/vela-core-shard-manager/parameter.cue
addons/vela-core-shard-manager/template.cue
test/e2e-test/addon-test/PENDING

[Addon] vela core shard manager

---

addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue

Feat: upgrade workflow addon version

---

.github/workflows/addon-test.yaml
addons/grafana/metadata.yaml
addons/grafana/resources/grafana-dashboard-kubevela-system.cue
addons/vela-core-shard-manager/metadata.yaml
addons/vela-core-shard-manager/parameter.cue
addons/vela-core-shard-manager/template.cue

Feat: update vela core shard manager & grafana

---

experimental/addons/redis-exporter/README.md
experimental/addons/redis-exporter/definitions/redis-exporter-component.cue
experimental/addons/redis-exporter/definitions/redis-exporter-trait.cue
experimental/addons/redis-exporter/metadata.yaml
experimental/addons/redis-exporter/template.yaml

Signed-off-by: HanMengnan <1448189829@qq.com>
I have:

[Addon] add redis exporter addon

---

addons/velaux/metadata.yaml
addons/velaux/resources/apiserver.cue
addons/velaux/resources/velaux.cue

[Addon] upgrade the VelaUX to 1.7.6

---

addons/rollout/definitions/rollout.cue
addons/rollout/metadata.yaml

rollout support statefulsets
I have:

[Addon] rollout: support statefulsets

---

addons/chartmuseum/metadata.yaml
addons/chartmuseum/resources/chartmuseum.cue
addons/chartmuseum/resources/parameter.cue

Support storageClassName in ChartMuseum PVC
I have:

[Addon] ChartMuseum: support storageClassName in PVC

---

addons/kruise-rollout/definitions/kruise-rollout.cue
addons/kruise-rollout/metadata.yaml
test/e2e-test/addon-test/definition-test/testdata/kruise-rollout/first-app.yaml

fix kruise-rollout and add test 
I have:

Fix:  fix kruise-rollout and add test 

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml
test/e2e-test/addon-test/definition-test/testdata/fluxcd/helm-component.yaml

1. If an addon defines its CRD resource in a plain YAML/CUE format, such as FluxCD, the CRDs can be updated during an upgrade. This has already been supported.
2. If an addon uses a Helm chart to install the CRD, this PR can support updating the CRD during an addon upgrade.
I have:

[Addon]: fluxcd addon helmrelease definition support upgrade crd

---

experimental/addons/velero/NOTES.cue
experimental/addons/velero/README.md
experimental/addons/velero/metadata.yaml
experimental/addons/velero/parameter.cue
experimental/addons/velero/resources/helm.cue
experimental/addons/velero/template.cue

Adds a basic scaffold for Velero addon.
Since most of the backup features will be implemented by whoever issue [#5483](https://github.com/kubevela/kubevela/issues/5483) is assigned to, currently this addon does nothing more than **installing and configuring Velero**. As for now, I will leave the majority of the backup features to that contributor. This addon will also be more feature-complete after that issue being resolved.
Users in a hurry can use Velero CLI or manually applying CR to backup. Later we will use `vela system backup` to do this.
Can successfully install and configure Velero with Amazon S3. 
Backup and restore abilities have been tested with s3.
I have:
- This …

[Addon] add basic velero addon

---

addons/fluxcd/metadata.yaml
addons/fluxcd/resources/components/helm-controller.cue
addons/fluxcd/resources/components/image-automation-controller.cue
addons/fluxcd/resources/components/image-reflector-controller.cue
addons/fluxcd/resources/components/kustomize-controller.cue
addons/fluxcd/resources/components/source-controller.cue

this commits adds metrics endpoint port to the controllers of fluxcd , therefore , users will be able to scrape the metrics of fluxcd metrics by defining their own podmonitor
I have:

[Addon] [fluxcd] chore: add ports to expose metrics endpoints for prometheus to scrape

---

experimental/addons/example/metadata.yaml

Feat: add plugin to example

---

.github/CODEOWNERS

Feat: update codeowner to remove unused entry

---

addons/o11y-definitions/definitions/grafana-dashboard-trait.cue
addons/o11y-definitions/metadata.yaml

Feat: support applies to any workload for grafana dashboard trait

---

.github/workflows/addon-test.yaml

Chore: refactor ci machine setup

---

addons/velaux/metadata.yaml

[Addon] Upgrade VelaUX to 1.8.1

---

addons/kruise-rollout/definitions/canary-deploy.cue
addons/kruise-rollout/definitions/rolling-release.cue
addons/kruise-rollout/metadata.yaml

rollout supports partition and canary

---

.github/workflows/addon-test.yaml
addons/fluxcd/config-templates/helm-repository.cue
addons/fluxcd/metadata.yaml

Signed-off-by: wuzhongjian wuzhongjian_yewu@cmss.chinamobile.com
support validate helm-repository properties
Fixes https://github.com/kubevela/kubevela/issues/5088
I have:

[Addon] support validate properties with CueX

---

addons/vela-workflow/definitions/chat-gpt.cue
addons/vela-workflow/metadata.yaml
addons/vela-workflow/parameter.cue

Feat: add chat-gpt workflow step and upgrade workflow version

---

.github/workflows/addon-test.yaml

Docker 20.10.24 cannot work with k3d now. Downgrade it to 20.10.17.
I have:

Fix: docker fix version

---

addons/ocm-hub-control-plane/readme.md

adds a section to describe the relationship between OCM and Cluster-Gateway.
Nothing to test
I have:

[Doc] chore: update readme for ocm-hub-control-plane addon

---

addons/cloudshell/metadata.yaml
addons/cloudshell/template.yaml

Fixes https://github.com/kubevela/kubevela/issues/6061
I have:

Fix: cloudshell image migration

---

addons/cert-manager/metadata.yaml
addons/cert-manager/parameter.cue
addons/cert-manager/resources/cert-manager.cue
addons/flink-kubernetes-operator/metadata.yaml
addons/flink-kubernetes-operator/parameter.cue
addons/flink-kubernetes-operator/template.cue
addons/ingress-nginx/metadata.yaml
addons/ingress-nginx/parameter.cue
addons/ingress-nginx/resources/ingress-nginx.cue
addons/keda/metadata.yaml
addons/keda/resources/helm.cue
addons/kruise-rollout/metadata.yaml
addons/kruise-rollout/parameter.cue
addons/kruise-rollout/template.cue
addons/model-serving/metadata.yaml
addons/model-serving/resources/ambassador.cue
addons/model-serving/resources/parameter.cue
addons/rollout/metadata.yaml
addons/rollout/parameter.cue
addons/rollout/resources/parameter.cue
addons/rollout/resources/rollout-controller.cue
addons/terraform/metadata.yaml
addons/terraform/resources/parameter.cue
addons/terraform/resources/terraform-controller.cue
addons/traefik/metadata.yaml
addons/traefik/resources/parameter.cue
addons/traefik/resources/traefik.cue
addons/trivy-operator/metadata.yaml
addons/trivy-operator/parameter.cue
addons/trivy-operator/resources/aqua-trivy-service.cue

Fixes #https://github.com/kubevela/kubevela/issues/3692
I have:

[Addon]Fix: add upgrade crds parameter when upgrading addon

---

addons/velaux/metadata.yaml

[Addon] upgrade the VelaUX to 1.9.1

---

.github/workflows/addon-test.yaml
addons/grafana/metadata.yaml
addons/grafana/resources/common.cue
addons/keda/metadata.yaml
addons/keda/template.cue
experimental/addons/clickhouse/metadata.yaml
experimental/addons/clickhouse/template.cue
experimental/addons/harbor/metadata.yaml
experimental/addons/harbor/template.cue
test/e2e-test/addon-test/PENDING

Fixes #[5965](https://github.com/kubevela/kubevela/issues/5965)
I have:

[Addon]Fix: modify render logic when clusters is nil about keda/grafana/clickhouse/harbor addon

---

addons/fluxcd/metadata.yaml
addons/fluxcd/resources/crds/bucket.cue
addons/fluxcd/resources/crds/git-repo.cue
addons/fluxcd/resources/crds/helm-chart.cue
addons/fluxcd/resources/crds/helm-release.cue
addons/fluxcd/resources/crds/helm-repo.cue
addons/fluxcd/resources/crds/image-policy.cue
addons/fluxcd/resources/crds/image-repo.cue
addons/fluxcd/resources/crds/image-update-automation.cue
addons/fluxcd/resources/crds/kustomize.cue
addons/fluxcd/resources/crds/oci-repo-new.cue

This is a temporary fix, the root cause is not found yet.
related issue: 
- https://github.com/kubevela/kubevela/issues/6171
- https://github.com/kubevela/kubevela/issues/6166
- https://github.com/kubevela/kubevela/issues/6150
I have:

remove fluxcd add crd status and bump version to fix installation failure

---

addons/terraform-tencent/definitions/terraform-tencent-sqlserver-instance.yaml
addons/terraform-tencent/metadata.yaml

[Addon] feat/add-terraform-tencent

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

refer to https://github.com/kubevela/catalog/pull/701
I have:

Bump terraform addon version and update chart repo url

---

addons/velaux/metadata.yaml

[Addon] upgrade the VelaUX to 1.9.2

---

hack/addons/syn_addon_package.go

[Addon] Fix: keep older version of addon when uploading artifacts

---

addons/terraform/metadata.yaml
addons/terraform/readme.md
addons/terraform/resources/terraform-controller.cue

Terraform addon 1.1.2 update to chart v0.7.12,because the chart of v0.7.11 are notwrk,
the values.yaml file in v0.7.11 are wrong.
enable addon by local,it works.
I have:

Bump terraform addon version 

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml

Signed-off-by: wuzhongjian wuzhongjian_yewu@cmss.chinamobile.com
I have:

Fix: helm release status default message shown

---

addons/velaux/metadata.yaml
addons/velaux/parameter.cue

Bump velaux to v1.9.3
- Support MySQL, Postgres/OpenGauss database driver support
I have:

[Addon] Bump velaux to v1.9.3

---

addons/dex/config-templates/dex-connector.cue
addons/dex/metadata.yaml
addons/dex/readme.md
addons/dex/schemas/config-uischema-dex-connector.yaml
addons/dex/template.yaml

* Upgrading the chart version to v0.15.3 in order to use the latest version of dex (v.2.37.0) (see https://artifacthub.io/packages/helm/dex/dex/0.15.3)
* Adding the support of the [OAuth connector] (https://dexidp.io/docs/connectors/oauth/)
I set arbitrary the new number version of the addon to 0.7.0 but feel free to change it accordingly to your policy
This version has been deployed and tested internally in our environment
I have:

[Addon] [dex] upgrade chart version and add support of oauth connector

---

addons/fluxcd/metadata.yaml
addons/fluxcd/schemas/config-uischema-helm-repository.yaml

fix: update fluxcd uischema

---

addons/vela-workflow/definitions/addon-operation.cue
addons/vela-workflow/metadata.yaml

Fixes kubevela/workflow#178
I have:

fix: add workflow name label in addon operation job

---

addons/fluxcd/definitions/kustomize.cue
addons/fluxcd/metadata.yaml

[Addon] fluxcd support decrypt in kustomize

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/definitions/kustomize.cue
addons/fluxcd/metadata.yaml
addons/fluxcd/resources/components/helm-controller.cue
addons/fluxcd/resources/components/image-automation-controller.cue
addons/fluxcd/resources/components/image-reflector-controller.cue
addons/fluxcd/resources/components/kustomize-controller.cue
addons/fluxcd/resources/components/source-controller.cue
addons/fluxcd/resources/crds/bucket.cue
addons/fluxcd/resources/crds/git-repo.cue
addons/fluxcd/resources/crds/helm-chart.cue
addons/fluxcd/resources/crds/helm-release.cue
addons/fluxcd/resources/crds/helm-repo.cue
addons/fluxcd/resources/crds/image-policy.cue
addons/fluxcd/resources/crds/image-repo.cue
addons/fluxcd/resources/crds/image-update-automation.cue
addons/fluxcd/resources/crds/kustomize.cue
addons/fluxcd/resources/crds/oci-repo-new.cue

This MR is exactly the same as #722, with the merge conflicts resolved. Anything in the description and the comments of that MR applies to this one as well. I forked off and fixed the conflicts myself (which were, btw, just on the version number of the plugin in `metadata.yaml`) because it seems like the original author (@kichristensen) moved on to a different project and forgot about this. Hope this expedites the merging and upgrade of the flux addon

[Addon] Update to Flux2 (fix conflicts)

---

addons/velaux/metadata.yaml

[Addon] Upgrade velaux version

---

addons/fluxcd/definitions/helm-release-def.cue
addons/fluxcd/metadata.yaml

to https://github.com/kubevela/catalog/issues/767, reverse pullInterval and interval in helmrelease
I have:

[Addon] to https://github.com/kubevela/catalog/issues/767, reverse pullInterval and interval in helmrelease
